### ISSUE TITLE
How do I set up express gateway to securely connect with my services

### ISSUE THREAD

**Issue by prof2k** [ExpressGateway/express-gateway#1008]
Hello. I have currently configured [express-gateway](https://www.express-gateway.io/) to communicate with a service on my backend exposed on a unique port on my machine and it's working fine. The gateway serves as a **proxy** to the services and currently does some security checks and **jwt authentication**. However, I'm concerned that if I don't put some sort of authentication on my service, then anyone who knows the port (or URL) my service runs on can directly access it and bypass the gateway directly. I'm looking for a way I can set up a sort of auth between the gateway and the service (maybe through keys) so that only the gateway can communicate with the services and not any other client. I currently can't find anything in the [docs](https://www.express-gateway.io/docs/) specifically for that. Also, if there's something wrong with my architecture, I'd appreciate it if you could point it out. Thank you. Would really appreciate any response as I've been on this for days and nobody is answering on stackoverflow.

**Comment by bhanuc** [comment]
Usually in such architectures, you would want to put the microservice in an VPC that is not accessible from outside and you refer to the microservice via its internal ip. Another alternative is to whitelist only certain ips (api gateway's ip) that can connect to the microservice instance.

**Comment by prof2k** [comment]
Yeah. I found out that it's more of an infrastructure problem. Thanks although I had to move from microservices due to the complexities associated with it. But think of it, can't there be a way to establish some sort of auth between the services and gateway through keys or whatever really? The problem with using IPs is that when scaling with say Kubernetes, and you are spinning up new clusters, you have new IPs entering the system and you'll have to probably manually add those new ips to your whitelist. And this might not be a very practical choice if it happens frequently.

**Comment by prof2k** [comment]
One way I found to solve the problem was to set up a private network within your services which cannot be accessed by external clients and only expose the gateway to the outside world. It's purely an infrastructure problem so you'll have to set it up on the hosting company where your services are hosted.
