### ISSUE TITLE
what is the roadmap for EG

### ISSUE THREAD

**Issue by woderchen** [ExpressGateway/express-gateway#1029]
Hi,
we are using EG in micro-service environment(all in node)  , so far the EG can supports large access for our system, about 100M+ daily visitors. it's amazing and outstanding. now we making long-term plan in team. but we found the EG is not updated yet for a long time, pls let me known the roadmap or next release date for EG, thanks.

**Comment by XVincentX** [comment]
See the readme for it. Essentially speaking, we are not developing Express Gateway anymore at this point.
