### ISSUE TITLE
Plugin Framework:  spec only

### ISSUE THREAD

**Issue by IrfanBaqui** [ExpressGateway/express-gateway#218]
Plugin Spec for policies (actions, conditions), db schemas and services

**Comment by altsang** [comment]
need docs/spec on the plugin system:

- [ ] what is a plugin?
- [ ] what is inside a plugin?
- [ ] how do you install?
- [ ] when you install a plugin - what happens? (i.e. register new custom entities)
- [ ] what is a list of ALL EG entities that you can include in a plugin
- [ ] how do you uninstall?
- [ ] when you uninstall a plugin - what happens? (i.e. unregister new custom entities)
- [ ] how do you see all plugins? (i.e. system.config..yml)
- [ ] are there Admin API endpoints related to plugins?
- [ ] are there CLI commands related to plugins? (i.e. eg doctor <pluginname>???)

**Comment by DrMegavolt** [comment]
https://gist.github.com/DrMegavolt/87af50ebbf6ae5bd0614477c21a0930b

**Comment by altsang** [comment]
updated spec (v3)  - https://docs.google.com/document/d/1jSDul2n_xbeKNtnek69M79-geur6aTWShAcBZ9evD0E/edit
