### ISSUE TITLE
Core: Support proxying WebSockets

### ISSUE THREAD

**Issue by geek** [ExpressGateway/express-gateway#278]
The http pipeline should support optional WebSocket proxying. This will require some refactoring so that the proxy policy has access to the http listener, so I understand if you don't want to go down this route.

**Comment by DrMegavolt** [comment]
web proxy support is now possible using `http-ready` `https-ready` `admin-ready` events
that provide access to http server 

doc is in this PR 
https://github.com/ExpressGateway/express-gateway.io/pull/179
