### ISSUE TITLE
JWT Plugin:  3rd part introspection capabilities

### ISSUE THREAD

**Issue by jimhw** [ExpressGateway/express-gateway#30]
A developer familiar with Express middleware should be able to take any middleware that extracts the parameters that are necessary to construct a configured instance of it to be passed dynamically when instantiating that middleware. 

Those parameters should go into EG config files in a standardized format.

**Comment by altsang** [comment]
we'll use JWT as the documented example of taking an off the shelf middleware for `passport-jwt`and turn into an EG policy

**Comment by altsang** [comment]
the JWT use case can be broken into two parts:
- JWT introspection and verification (an authoritative source other than EG)
- EG credential management introducing a new token type - JWT,  validating, generating and maintaining these tokens as part of the existing token service

this user story covers #1

**Comment by XVincentX** [comment]
Introspection capabilities have been implemented, I'm closing this.
