### ISSUE TITLE
Add key-auth support to CLI so it can authenticate against Admin API that is protected with key-auth

### ISSUE THREAD

**Issue by DrMegavolt** [ExpressGateway/express-gateway#300]

**Comment by altsang** [comment]
- out of the box - no protection for the admin API endpoint to hinder the CLI from working
- the admin API can be protected with any of the auth policies that EG supports
- in docs, under admin API - please update with full example of going through and doing so with key-auth, passing a header as env variable to 
- `-H authorizationheader:keyvalue` - use env variable to populate or alias the command
