### ISSUE TITLE
E14/S1: Ability to passing upstream and downstream headers

### ISSUE THREAD

**Issue by jimhw** [ExpressGateway/express-gateway#31]
Ability to passing in EG custom headers downstream so that use cases like path tracing, audit, request/response time introspection and metadata can be realized.

EG should be able to inject, modify and preserve upstream and downstream headers as needed for its own instrumentation as well as preserving system metadata for consumers and backend producers.

**Comment by altsang** [comment]
right now the expression policy allows you to do this
