### ISSUE TITLE
CLI Users, Apps, Creds Create should be consistent

### ISSUE THREAD

**Issue by DrMegavolt** [ExpressGateway/express-gateway#311]
User create - output id or username depending on q

App Create outputs id

Credential Create - dumps entire object

Also -v flag
I propose to use it to show info similar to `curl -v google.com`

* some debug info
\> request data
< response data

**Comment by altsang** [comment]
let's clean up the output to make consistent - @DrMegavolt pls doc proposal, let's do `-v` in a separate story

**Comment by DrMegavolt** [comment]
1) No flags cli command:
output to stderr checkmark\cross and Success\Fail message
output to stdout JSON with newly created entity

2) -q provided 
output to stdout  just id (user id, app id, credential id )

3)  --config parameter to be removed

@kevinswiber @altsang , correct ?

**Comment by kevinswiber** [comment]
Looks good to me.

**Comment by altsang** [comment]
👍
