### ISSUE TITLE
Proxy Policy: add more load balancing strategies

### ISSUE THREAD

**Issue by kevinswiber** [ExpressGateway/express-gateway#324]
Several options are available for load balancing algorithms.

- Round robin
- Weighted round robin
- Random
- Least connections
- Custom

Extra credit: Consistent Hashing with Bounded Loads (https://arxiv.org/pdf/1608.01350.pdf)

**Comment by kevinswiber** [comment]
This will give birth to new feature requests, as well: health checks, dynamic routing, service discovery, etc.

**Comment by altsang** [comment]
added to feathub - http://feathub.com/ExpressGateway/express-gateway/+30
