### ISSUE TITLE
Core: Circuit Breaker Pattern (optionally including Retry Mechanism with Exponential Back-off)

### ISSUE THREAD

**Issue by kevinswiber** [ExpressGateway/express-gateway#325]
What happens when a service endpoint appears down?

1. Retry request a fixed number of times with an exponential backoff.
2. If the exponential back-off reaches a limit, perhaps this isn't a transient fault.  Open the Circuit Breaker.
3. Subsequent requests fail fast without communicating to the service endpoint.
4. After a set time, the circuit breaker allows another request to go through.
5. If the request succeeds, close the circuit breaker and let traffic flow normally

**Comment by altsang** [comment]
added to feathub - http://feathub.com/ExpressGateway/express-gateway/+29
