### ISSUE TITLE
Config file watcher on network mount won't recognize changes

### ISSUE THREAD

**Issue by kevinswiber** [ExpressGateway/express-gateway#336]
When running in Docker with the config on a mounted volume, for example, Express Gateway doesn't recognize the change.

It's possible to change this using `usePolling: true` in the chokidar options, but there's a performance penalty.

See discussion here: https://github.com/paulmillr/chokidar/issues/242

**Comment by kevinswiber** [comment]
Could potentially implement this workaround: https://github.com/paulmillr/chokidar/issues/242#issuecomment-135859497

**Comment by DrMegavolt** [comment]
It is fixable using `CHOKIDAR_USEPOLLING`env var
ENV CHOKIDAR_USEPOLLING true
