### ISSUE TITLE
Data access should fail fast when database isn't connected and reconnection logic

### ISSUE THREAD

**Issue by kevinswiber** [ExpressGateway/express-gateway#338]
The Redis client will continuously try to connect with an exponential back-off.  While this happens, commands build up in a queue.

This means any API call requiring authorization hangs until an HTTP connection timeout is reached (possibly on the client).

Since we know the database isn't ready, we should fail fast.  The same is true for the Admin API / CLI.

Setting `enable_offline_queue` to `false` on the Redis client might be an option.  Otherwise, we can set our own flag on the client `ready` event and fail if the flag is falsey.

https://github.com/NodeRedis/node_redis#options-object-properties

**Comment by DrMegavolt** [comment]
we should use `retry_strategy` it allows try several times, set delays between retries and override error with friendly messages

**Comment by kevinswiber** [comment]
@DrMegavolt It has a default retry strategy that's pretty good, actually, depending on the use case.

I think we need to figure out:

1. Where is Express Gateway utilizing data access? (e.g., entity administration, authorization enforcement, etc.)
2. What is a reasonable amount of resilience to put behind the data access call? (e.g., retry 3 times with exponential back-off, wait for 45 seconds before failing, etc.)

If the resilience requirements for all data access utilization are the same, we should adjust them accordingly in `db.js`.  If they're different, we should consider getting rid of a single, global client used for all use cases.

**Comment by altsang** [comment]
while discussing with @rlisagor - if we deploy in an orchestrator like Kubernetes, we can't always guarantee deployment order and should have some kind of re-connection logic, but without server start and being ready for transacting

**Comment by XVincentX** [comment]
@altsang Can you have a look here and instruct how we want to proceed? If this is not relevant anymore, I could close this.
