### ISSUE TITLE
Service Discovery: integrate with service discovery mechanisms - spec

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#348]

**Comment by kevinswiber** [comment]
Spec: https://docs.google.com/document/d/1wkpcVGAnI2rQzetMJ6QVHUrE9TBXf0YvxqYAWUsCerY/edit?usp=sharing

**Comment by altsang** [comment]
per our discussion, the current thinking is to build a reference implementation for service discovery to Kubernetes DNS:

- make service discovery for Kube DNS a plugin
- the plugin will expose Kubernetes services to EG available to be mapped as service endpoints
- proxy policy can load balance between service endpoints exposed by Kube DNS
- serve as a reference implementation for how to utilize DNS based service discovery for other offerings like Consul
