### ISSUE TITLE
Abstract DB to support different datastore

### ISSUE THREAD

**Issue by roccomuso** [ExpressGateway/express-gateway#354]
Do you have any plan to abstract `db.js` to support multiple storage mechanism?

**Comment by IrfanBaqui** [comment]
Yes, we would like to support databases beyond just Redis. But it's not just a matter of abstracting `db.js`, as the DAOs in the consumer management and credential modules will need to change too. It'll be a decent sized refactor, but something we definitely plan to support.

**Comment by IrfanBaqui** [comment]
We're also open to PRs if you'd like to take it on :)

**Comment by altsang** [comment]
will consider different datastore on a per basis - closing and added postgres into feathub
