### ISSUE TITLE
Queuing support

### ISSUE THREAD

**Issue by AmreeshTyagi** [ExpressGateway/express-gateway#355]
Implement queuing mechanism either using Kafka or redis.

**Comment by kevinswiber** [comment]
Hey, @AmreeshTyagi.  Can you elaborate on what you mean by "queuing mechanism?"  What's the use case?  What gets queued?

Thanks.

**Comment by altsang** [comment]
waiting on response from @AmreeshTyagi for more info, closing in meantime
