### ISSUE TITLE
Rate limiting feature

### ISSUE THREAD

**Issue by AmreeshTyagi** [ExpressGateway/express-gateway#356]
Create a plug-in to support rate limiting feature.

**Comment by kevinswiber** [comment]
@AmreeshTyagi, we do have a rate limiter policy built-in: http://www.express-gateway.io/docs/policies/rate-limiter

Were you looking for something more?

Distributed rate limiting is up for discussion.  The current implementation expresses limits that are local to the gateway instance.

**Comment by altsang** [comment]
waiting for response from @AmreeshTyagi , closing in meantime
