### ISSUE TITLE
Add Greenkeeper to keep a tab on dependency version updates.

### ISSUE THREAD

**Issue by sachingill** [ExpressGateway/express-gateway#360]
[Greenkeeper NPM repo link](https://www.npmjs.com/package/greenkeeper).
[Greenkeeper Page](https://greenkeeper.io/)l.

Not able to add any label for it. Can someone move it to enhancement/  good to have.

**Comment by DrMegavolt** [comment]
@sachingill why do we need it ? it seems to just try to install latest packages allowed and test if it works. 
we have exact version fix. https://github.com/ExpressGateway/express-gateway/blob/master/package.json as well as package-lock.json
