### ISSUE TITLE
CLI does not work in windows

### ISSUE THREAD

**Issue by julianfrank** [ExpressGateway/express-gateway#362]
I installed express-gateway using npm as per the getting started guide...but CLI does not work...doesn't show any error message as well...

I tried in linux and it works perfectly!

**Comment by kevinswiber** [comment]
Hey, @julianfrank!  I'll look into this.  What version of Windows are you running? What version of Node?  What version of NPM?

Thanks!

**Comment by kevinswiber** [comment]
Running on Node 8.2.1, npm 5.3.0, and Windows 10... I see the issue.  Looking into it now.

**Comment by kevinswiber** [comment]
@julianfrank There's a PR in now to fix this issue.

The CLI will execute globally for `eg gateway create`.

When the working directory is in the path of a gateway instance, the global `eg` should delegate to the CLI that's installed locally (in `node_modules\.bin`).  This helps to ensure the executing CLI code is paired with the exact version of the installed `express-gateway` module.

The code that does this delegation was looking for `node_modules\.bin\eg`, which of course, works everywhere except Windows.  The PR (#364) will change this file to `eg.cmd` if the current platform is Windows.

**Comment by julianfrank** [comment]
Thanks for the update... I'll wait for next release then

**Comment by kevinswiber** [comment]
@julianfrank This update has been released in v1.1.1.  Sorry for the delay!

**Comment by kiriti999** [comment]
Its still the same issue in windows 10. "eg commands" are stuck

**Comment by sathishsatzy** [comment]
> Its still the same issue in windows 10. "eg commands" are stuck
@kiriti999 Add express-gateway's installation path ( C:\Users\sathish\AppData\Roaming\npm ) in environment variables and check with eg commands it will work.
