### ISSUE TITLE
Provide ability to resolve SRV record while using proxy 

### ISSUE THREAD

**Issue by saswatds** [ExpressGateway/express-gateway#369]
Using srv record for service discovery using internal dns is kind of a practise. If there is a feature by which the serviceEndpoint can take in an srv record and then resolve the service accordingly will be a great addon

**Comment by kevinswiber** [comment]
Hi, @saswatds.  There's an issue to spec out Service Discovery here: https://github.com/ExpressGateway/express-gateway/issues/348

You can see what's written about DNS SRV records here, as it relates specifically to Consul: https://docs.google.com/document/d/1wkpcVGAnI2rQzetMJ6QVHUrE9TBXf0YvxqYAWUsCerY/edit#heading=h.wfvqhxlmxbca

My hope is that we can build Service Discovery Providers, making this an extensibility point in Express Gateway.  You should be able to comment on the Google Doc above, and we would love to have more input.

**Comment by kevinswiber** [comment]
Closing in favor of #348.
