### ISSUE TITLE
How to implement transaction?

### ISSUE THREAD

**Issue by campanagerald** [ExpressGateway/express-gateway#372]
how can i implement transaction from different services using express-gateway? Is there a way when the gateway can execute a commit command?

**Comment by kevinswiber** [comment]
Hey, @campanagerald.  Can you provide or point to an example of what you're trying to achieve?  Perhaps a deeper explanation might suffice.

**Comment by campanagerald** [comment]
Lets say I have 2 micro-services (separate application, different database). How can I execute transaction in each micro-services without data inconsistency? 

This is the scenario: The user will request a plan (Premium)
I have Account service and Account-Plan service, Account service will first save the account and user details, after that, the Account-Plan service will get the details of account and user and then it will create a plan.

**Comment by kevinswiber** [comment]
The coordination has to live somewhere.  Putting it in a gateway might be overloading the responsibilities a little bit.  Currently, this isn't possible to do in Express Gateway.  We are discussing a plugin system that _should_ allow this sort of behavior through custom code.  See here: https://docs.google.com/document/d/1jSDul2n_xbeKNtnek69M79-geur6aTWShAcBZ9evD0E/edit

**Comment by campanagerald** [comment]
This is what i want to achieve. please see this link https://blog.risingstack.com/building-an-api-gateway-using-nodejs/ and Data aggregation. Thanks. hope its possible.

**Comment by kevinswiber** [comment]
Scatter-gather is not currently possible through Express Gateway's `proxy` policy.  This functionality will be attainable through a custom plugin once the plugin system is in place.
