### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by pinalbhatt** [ExpressGateway/express-gateway#374]
Getting following error while trying to install with `sudo npm install -g express-gateway` on both node 6.11.2 and node 8.2.1

`
$ sudo npm install -g express-gateway
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/Users/a.b/.npm-global/bin/eg -> /Users/a.b/.npm-global/lib/node_modules/express-gateway/bin/index.js

> fsevents@1.1.2 install /Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/fsevents
> node install

[fsevents] Success: "/Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> bcrypt@1.0.2 install /Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@8.2.1 (node-v57 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/bcrypt/build'
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/a.b/.npm-global/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/bcrypt
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/a.b/.npm-global/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:921:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/bcrypt
node-pre-gyp ERR! node -v v8.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /Users/a.b/.npm-global/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/a.b/.npm-global/lib/node_modules/express-gateway/node_modules/bcrypt/lib/binding' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/a.b/.npm/_logs/2017-08-09T13_15_46_067Z-debug.log
`

**Comment by altsang** [comment]
@pinalbhatt did you `sudo` install Node? the log above says that for some reason you can't download the pre-compiled binary for `bcrypt`, it you click on that link in your browser it works, also it's defaulting to trying to compile and doesn't have access to the directory within `/Users` on your machine, this doesn't appear to have to do with Express Gateway itself

**Comment by kevinswiber** [comment]
@pinalbhatt See if this can be of any help: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by altsang** [comment]
closing in meantime
