### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by demetriusnunes** [ExpressGateway/express-gateway#378]
As I was evaluating express-gateway I performed a quick benchmark comparing hitting my API directly and through a straight proxy pipeline in EG.

Although a better performance from hitting the API directly is expected, the transaction rate was almost 2x larger than going through the proxy endpoint (529 t/s x 272 t/s on average).

That sounds like too much overhead for a simple direct proxy.

**Comment by altsang** [comment]
hey @demetriusnunes, thanks for letting us know - totally agree. Just want to understand - you have only one pipeline and you're using a proxy policy just to see what overhead EG imposes correct?

We'd like to improve EG so  I wanted to make sure I understand your config use case

**Comment by demetriusnunes** [comment]
That's correct.

Although, yesterday I did further testing on most popular NodeJS proxy libraries (node-http-proxy, bouncy, redbird, express-http-proxy) and the results were all pretty similar, so it just might not be an issue with EG itself.

If you could do another investigation on your side, would be great to confirm this.

**Comment by DrMegavolt** [comment]
@demetriusnunes It really depends on environment and the way you test. So numbers can vary. 
I have test on dedicated VM 4 cores, with EG runs in docker container and `ab` tool runs in different docker container to not affect results, "backend" downstream service is in another   docker instance

1 Endpoint, 1 pipeline,  

Raw node.JS hello world => 3000-3500 rps
EG with proxy only policy => 1100-1200 rps
<img width="1198" alt="screen shot 2017-08-01 at 3 27 42 pm" src="https://user-images.githubusercontent.com/2204898/29448215-395c8038-83fe-11e7-9d89-d7f6bb965d3a.png">
Non EG but just http-proxy module usage will give similar results, so EG overhead is quite minimal for this setup

for key-auth + proxy it is 800rps
<img width="1224" alt="screen shot 2017-08-01 at 12 17 34 pm" src="https://user-images.githubusercontent.com/2204898/29448245-538d19ea-83fe-11e7-9e1e-f8d4b44a527a.png">

**Comment by DrMegavolt** [comment]
And for proxy in general it is not that simple as `res.send('hello world')`
As rough assumption I would expect  proxy  to drop ~2 times in performance because node.js now maintains two times more connections per request 

Obviously HA proxy or nginx will be faster, and there is no way node.js based solution can outperform them. But the absolute numbers in my test results seems to be good enough for most use cases. And once clustering is implemented EG will be capable handling any load
