### ISSUE TITLE
Why not using mainstream Kong?

### ISSUE THREAD

**Issue by tomford56** [ExpressGateway/express-gateway#379]
how is it better?

**Comment by jingsam** [comment]
It's nodejs based, easy to be extended.

**Comment by altsang** [comment]
bingo - and the extensions aren't all backed by one company like Mashape, EG's goal is to galvanize all existing middleware for Express and roll it into the API gateway use case for what you need and are already familiar with, extending Kong means using Lua and creating something greenfield as a starting point
