### ISSUE TITLE
Guidelines to submit an issue

### ISSUE THREAD

**Issue by niksmac** [ExpressGateway/express-gateway#380]
I think, we need to have some guidelines to commit issue. Something like [cra](https://github.com/facebookincubator/create-react-app/issues/new) 

Since EG is a middleman most of the time, we cannot be sure that the issue is with EG itself so steps to recreate the issue isa must have. For example #378

**Comment by altsang** [comment]
@niksmac  - yup fully agree, let me think how we can clarify some basic steps in the contributor guide as well maybe look at GH issue templates 👍
