### ISSUE TITLE
Delete Credential  CLI command (and REST api ) is missing 

### ISSUE THREAD

**Issue by DrMegavolt** [ExpressGateway/express-gateway#383]
@ahwing210 found that no delete credential is implemented

**Comment by altsang** [comment]
@awhing210 - you can deactivate credentials, which will preserve the complete history for audit purposes and there is an archive that happens as well - if we filtered deactivated credentials from the `list` command  - would this work for you?  Trying to understand if you really need a hard delete and why? thx!

**Comment by altsang** [comment]
make `list` command by default not to show deactivated credentials, add option to show deactivated, active, or both

**Comment by XVincentX** [comment]
This has been done in #428 and will land in EG 1.3.
