### ISSUE TITLE
Admin: extend API to be configured with host and http/https

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#384]

**Comment by DrMegavolt** [comment]
No reload assumed, API it will just update gateway.config

**Comment by DrMegavolt** [comment]
EG Admin API should not responsible for that. since it cannot properly restart the Gateway. It should be infrastructure level concern

**Comment by DrMegavolt** [comment]
@altsang can we cancel this task?

**Comment by altsang** [comment]
yup, closing and created #467
