### ISSUE TITLE
Admin: extend API to include pipelines

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#386]

**Comment by DrMegavolt** [comment]
Assuming  it will add new pipeline with 'name' and either will contain no policies or will include some dummy policy if YAWN is not fixed

**Comment by DrMegavolt** [comment]
this task is  to define API endpoints for granular Pipelines API 
https://docs.google.com/document/d/1qgeYckdTuoQE24wZrju40jef92nTeNO0nIQXyfsCA38/edit?ts=59cdf8d8#

@altsang Please define at what level we need to stop in this spec

**Comment by XVincentX** [comment]
@DrMegavolt Can we close this? We have such API now.

**Comment by DrMegavolt** [comment]
closing as duplicate of #418. Already implemented
