### ISSUE TITLE
Plugin Framework: doc rewrite policy as Express Gateway plugin

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#393]

**Comment by XVincentX** [comment]
@altsang Is this about updating the documentation about the plugin?

**Comment by altsang** [comment]
yep - doc should in expressgateway/express-gateway.io

**Comment by XVincentX** [comment]
@altsang I think we should probably sync here. Do we want to get a plugin subsection and call it *Official Plugins*, or you want to put some links to a page on the *Resources* page?

Also - do you think that the [README](https://github.com/ExpressGateway/express-gateway-plugin-rewrite) is good enough?

**Comment by altsang** [comment]
sorry for the confusion - when we say docs we mean the documentation section - http://www.express-gateway.io/docs/ not the EG website, our webdev and visual designer will add to the resources pages
