### ISSUE TITLE
Admin: single source of truth "library" for REST and offline

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#395]
- surface REST API (extension of the Admin API)
- CLI Yeoman generator (against a EG instance - locally)

**Comment by DrMegavolt** [comment]
Note: it may be significantly easier to make CLI start it's own EG admin API server instead of extracting into some lib

**Comment by altsang** [comment]
@DrMegavolt  REST and CLI are going through the same libraries right? with CLI utilizing REST when needed for remote?
