### ISSUE TITLE
Plugin Framework: eg cli extension to do plugin installation and manipulate `system.config.yml` and `gateway.config.yml`

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#396]

**Comment by altsang** [comment]
### Use Case 1
`eg plugin install example` - installed express-gateway-plugin-example by convention "example" plugin
system.config.yml - adds an entry into `plugins:` section with global plugin parameters 
gateway.config.yml - adds an entry into `policies:`

### Use Case 2
`eg plug install acme-org-eg-plugin-superauth` - installs `acme-org-eg-plugin-superauth` with specified package name - "superauth" plugin

system.config.yml - adds an entry into `plugins:` with `package"`name

### Some kind of "Schema"  for plugin metadata
- sample use case - expose through CLI (prompting)
- list of plugin contents
- validation

**Comment by agokjr** [comment]
What about plugins that are ether in a npm scope registry eg `@acme-org/plugin-superauth` or a private registry?
