### ISSUE TITLE
Plugin Framework: e2e test - install rewrite plugin using eg cli

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#398]

**Comment by XVincentX** [comment]
@altsang Where do you think should these tests live? `express-gateway` or `express-gateway-plugin-rewrite`?

In my opinion all core-plugin-installation-tests should be living in the `express-gateway` repository - so every time we modify the core we know if it's breaking the integration with the officially supported plugins.

On the other hand, keeping these tests in the plugin repository won't give us this advantage, as the gateway version is pinned in [the plugin itself](https://github.com/ExpressGateway/express-gateway-plugin-rewrite/blob/feature/init/package.json#L26).

What do you think?

**Comment by altsang** [comment]
I think we should be a test harness that can be used by any EG plugin developer that:
1. installs eg (the latest release)
2. installs the plugin
3. runs e2e tests in detail that exercises all the major functions of the plugin

the EG core can have a e2e test that installs all known EG official plugins to smoke test compatibility at a higher level

if the ecosystem of plugins grows well beyond the EG official plugins, then the self check/self test approach would have higher leverage in the long rum

**Comment by DrMegavolt** [comment]
#422 has a discussion on testing tools. probably this can be the plugin to verify the approach
