### ISSUE TITLE
Admin UI

### ISSUE THREAD

**Issue by agonbina** [ExpressGateway/express-gateway#399]
I was just curious to know if there are any plans to build an administration interface for the admin API?
I would be able to contribute to its development.

**Comment by altsang** [comment]
hi @agonbina, we'll be extending the admin API to continue to include CLI as an interface. the UI within LunchBadger will be a commercial offering for such thing

**Comment by kevinswiber** [comment]
@agonbina No plans to build an Admin UI at the moment.  If you'd like to get the project started, I'd say go for it! 

We have an Admin API Reference here: http://www.express-gateway.io/docs/admin/

When you run the gateway, it'll start the Admin API.  Once it's running, you can access a Swagger UI for visualizing the API here: http://localhost:9876/api-docs/.  That might help get you started!

**Comment by NatarajanGanapathi-Hexaware** [comment]
@kevinswiber I am unable to access `http://localhost:9876/api-docs/` from my local deployment. I have added `admin:  host: localhost   port: 9876` in `gateway.config.yml` file. Do I need to do anything more?

**Comment by ggcaponetto** [comment]
@agonbina I started an open source gui project for express-gateway. Feel free to check it out while it's in development. https://github.com/ggcaponetto/express-gateway-gui
