### ISSUE TITLE
Plugin Framework: eg plugin install example not writing policies to gateway.config.yml

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#414]
steps to reproduce:

npm install -g express-gateway
eg gateway create (demogateway)
cd demogateway
eg plugin install example
in gateway.config.yml under policies: expected an example entry but don't find one

we should create an e2e test to make sure all facets of the plugin example are installed correctly

**Comment by kevinswiber** [comment]
You're installing the package named "example" (http://npm.im/example) with
that command. Currently, on install, the CLI doesn't try to prepend the
prefix, as this isn't as easy as it may sound given the various package
specifier options. It also doesn't validate the installed plugin. This
should log an error.

eg plugin install express-gateway-example-plugin should get you there.
Also, need to make sure the manifest has a top-level policies array. This
is covered in the e2e test IIRC.
