### ISSUE TITLE
Clustering: Multiple EG instances with central configuration - spec only

### ISSUE THREAD

**Issue by jimhw** [ExpressGateway/express-gateway#43]
As an EG admin, I would want to be able to configure multiple EG instances that are all driven off central configuration, so that I have scale and high availability.

An EG admin should be able to create mutiple gateway instances that are assigned different configurations but also share centralized information.

Example:
Gateway 1: has 2 pipelines and fronts /catalog and /cart public endpoints
Gateway 2: has 1 pipeline and fronts /user endpoint
Both Gateway 1 and 2 should share the same set of API consumer data for access and assignment

**Comment by IrfanBaqui** [comment]
Clustering can be performed in multiple ways, but the ideal scenario would be to leverage containers and orchestrate them.

To do this, I propose we dockerize EG (I think EG is already dockerized, but need to test it), and orchestrate the containers with kubernetes. The configuration would be centralized in the process.

**Comment by IrfanBaqui** [comment]
https://docs.google.com/a/lunchbadger.com/document/d/120W_jbbMfdqxIkHKtmgsITizsC7gEfeF0Kc4sUKri2I/edit?usp=sharing

**Comment by DrMegavolt** [comment]
Config engine related 
https://docs.google.com/document/d/1HrC75oHWeQG-50JjglR1UkkuzV4JUaUyrpDiMtE7Wgk/edit

**Comment by stanislaw-glogowski** [comment]
Just another point of view:
https://docs.google.com/a/lunchbadger.com/document/d/1nKgkEBK2JaREaJC3vNvKWsLkzzFiUonkcLIa4TFeWTc/edit?usp=sharing

**Comment by kevinswiber** [comment]
Should look at distributed rate limiting as a first use case.
