### ISSUE TITLE
Provide a Typescript interface for plugin framework

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#433]
Although we have a [great documentation](http://www.express-gateway.io/docs/plugins/plugin-development) for developing a plugin, it might be worth and lowering the barriers for people willing to write a plugin to provide a typescript definition - even people using javascript would benefit it, if using the right [IDE](https://code.visualstudio.com).

**Comment by DrMegavolt** [comment]
from Slack, for history serhii.kuts [4:10 PM] 
@XVincentX   I got the idea about @types. 
the way it works is it uses `@types/package-name` package with same version `package-name` version 
or it looks for `"types": "./lib/main.d.ts"` in the package.json of the imported package

and once you do `const _ = require('lodash')` IDE is showing autocomplete options. this is how it knows that `_` is actually *lodash*

the problem is that we don’t have Plugin SDK so there is nothing we can reference, and both approaches will not work. 

So it is either create SDK kind of plugin framework 
Or ask people to manually copy some ts file into their plugin (and auto include the file with CLI `eg plugin generate` )  

Are there other alternatives ?

**Comment by XVincentX** [comment]
@DrMegavolt I've been looking around for all the solution and here's what I think would probably be the best combination.

I've also created a POF that should validate the thing.

I'd avoid (at least for now) to provide an SDK plugin framework, as the API surface we're exposing is still small and I think it's going to change quickly - we might have an huge overhead to keep the SDK updated; therefore I'd defer this idea for the future.

I like the concept of embedding the definitions with the plugin scaffolder - even though I see two problems:

1. If I do not want to use the scaffolder for some reason I won't have the typings unless I would look for them in some repository and manually copy-paste them in my project.

2. If I create a plugin using the scaffolder and a new API is released and I want to update my project to use the new features I'll have to update my definitions that is - I'll have to manually look for them and copy paste them in my project.

**But!**

If you're writing a plugin for the express-gateway, it's very likely you'll want to test it somehow to see if it's playing correctly with the gateway: fundamentally `express-gateway` it's going to be a `devDepencency`

Given this foreword:

1. We could embed the [plugin typings](https://github.com/ExpressGateway/express-gateway/compare/features/plugin-typings?expand=1#diff-b43b38f76e7ff42c526a7a311616f40c) in the `express-gateway` itself, as an artifact.

2. An user that's writing a plugin for the gateway, saving `express-gateway` as a devDepedency, will just need to [import our file and enable the type checker](https://github.com/ExpressGateway/express-gateway-plugin-rewrite/compare/XVincentX/use-types?expand=1#diff-36598ac1b037cb0f3cfacf5ef926ee80). If they're using Typescript directly, it would be even easier and straightforward.

In this way:

1. Scaffolding or not scaffolding, I'll always have types.
2. If I want to develop for a newer Plugin API, I just need to update my devDependency (that would be needed anyway since I want to test the plugin with the right gateway version)
3. ByProduct: If one day, for some reason, we would like to switch to Typescript - we're already set. No plugin will break.

Here's an example, using the branches I linked you above:

![](https://media.giphy.com/media/3ov9k8IG1RTgcfwrzG/giphy.gif)

//cc @kevinswiber 

What do you guys think?

**Comment by DrMegavolt** [comment]
looks like what what is needed. Just need to ensure that plugins are installed in production mode without devDep

**Comment by XVincentX** [comment]
👍 - I'll keep going with the typings and make sure they're accurate.

About the verification - we're already good here.
If you run `npm install` with `NODE_ENV=production` all `devDependencies` are automatically skipped.

**Comment by DrMegavolt** [comment]
as developer you don't run in production. 
but unlikely you need express-gateway loading self as dependency  

will it work  using npm link so plugin will be referencing exactly the same version of eg ? 
so it will be EG -> require plugin -> require EG

**Comment by XVincentX** [comment]
🤔 I am not sure I understand what you're trying to say.

So - if you `npm install` with `--production` or `NODE_ENV=production`, it will not install development dependencies listed in `package.json`

Regardless of this flag (production or not production), development dependencies for dependencies listed in `package.json` are never installed.

So if I have this scenario

```json
  "dependencies": {
    "express-gateway-plugin-rewrite": "1.0.0"
}
```

Its development dependencies will never be installed - in any environment (production or not production)

I do not see any problem with using it with `npm link` - it should work fine.

**Comment by DrMegavolt** [comment]
ok, you are right
