### ISSUE TITLE
When installing any plugin, the new system.config.yml is invalid

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#438]
## Steps to reproduce
1. Create a new gateway `eg gateway create test`
2. Install any plugin `eg plugin install express-gateway-plugin-rewrite`
3. Inspect the `system.config.yml` file - you'll see the `plugin` section has a new line that invalidates the whole thing.

**Comment by DrMegavolt** [comment]
@kevinswiber can you remind the point where it breaks
