### ISSUE TITLE
investigate Passport LocalStrategy for memory consumption

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#443]
### Entering Issues
For enhancements or feature requests, do no enter an issue here, instead please use the [Express Gateway Feathub](https://feathub.com/ExpressGateway/express-gateway), this helps the team prioritize and allows upvoting for everyone.

For all other issues:
- [x] please choose a label: `Question` or `Bug`
- [ ] for `Bug`(s) please include steps to reproduce and any supporting info that might be helpful e.g. `gateway.config.yml`

For `Question`(s) please consider using the [Express Gateway Gitter](https://gitter.im/ExpressGateway/express-gateway) for a real time response instead.

**Comment by altsang** [comment]
Per @Kalevera...

<blockquote>
Roberto @Kalevera Sep 27 21:31
@altsang yes, when implementing passport strategies most of the strategies are implement by initializing a local object. In the case of the the passport-oauth-strategy it's extending an object that initializes a JS object that's holding the state of an authenticated user. It appears the once the user gets a token they are authenticated against this instance. The issue is the node and express were made so that they don't hold state. They're input and output. Every time a user is being initialized by passport it's creating a new object that's not going to garbage collection. So as new users connect and become authenticated they're objects remain in memory. Thus leaving less memory for the application it self. If the user base grows then you end up with more and more memory being used by these instances.
There's a need to trigger garbage collection on instances that aren't being used. Just a few ways that i would manage this would be have a separate node instance that's running as a cache layer so that every so often I would check to see if a user has been authenticated within XX amount of hours or days.
Depending on the type of application I may decide to issue a renewal token, with the purpose of using the token to re-authenticate the user on the same device. If this token hits the gateway have the request check with the authentication database to determine if the token was issued by the system then generate a new session token so the user would be put back into the cache layer. The idea being that if they're hitting the gateway with a renewal token they actually have to go all the way to the database to be authenticated by the system. To the user it would seem like the app is taking a bit longer than usual to load the contents. If they're using the app frequently you may want their experience to stay speedy so the option is to update their last time in the request. so that when the garbage collection occurs their session token doesn't get removed.
The reason i would implement a second instance of node is so that request can be async and go to the cache layer. That way the memory is all on the second instance and if it continues to grow the admin can scale that portion of the app as needed.
</blockquote>

**Comment by Kalevera** [comment]
I think I saw in gitter chat that the user data from passport is being stored in redis. Try using the EXPIRE feature in redis on the passport instances so that you can trigger garbage collection. Update the EXPIRE if they get new tokens as described in my write up. 

Sorry don't have the time resources to help on this item.

**Comment by indolent-developer** [comment]
I see the tag of helpwanted on this. I can offer some let me know how.

**Comment by XVincentX** [comment]
@indolent-developer Sorry for the late reply. We haven't scheduled this issue yet, therefore we'd love to get help from somebody outside.

If you're still up to it, please go!

**Comment by DrMegavolt** [comment]
By default it was using express-session default in memory store that is not production ready as session store. 

Starting from 1.6.0 #601 we support other session providers. So sessions will not be stored in memory. 

Feel free to reopen the ticket if it doesn't solve the issue
