### ISSUE TITLE
Variable Substitution in Config Files

### ISSUE THREAD

**Issue by kevinswiber** [ExpressGateway/express-gateway#444]
To handle configuration that can survive across environments (dev, CI, staging, prod), we need to be able to use environment variables in config files.

Dockerfiles have a method derived from Bash's parameter expansion syntax.  It would be great to have something similar.  Reference: https://docs.docker.com/engine/reference/builder/#environment-replacement

One potential conflict is that some policies use template literals that take advantage of JavaScript's expression interpolation.  Note the usage of `rateLimitBy` in the `rate-limit` policy here: http://www.express-gateway.io/docs/policies/rate-limiter#options-reference

To overcome this obstacle, we can alter the variable substitution syntax to be: `${{REDIS_HOST}}`. An example of assigning a default should the environment variable not exist: `${{REDIS_HOST:-localhost}}`.

Happy to discuss alternatives.

**Comment by DrMegavolt** [comment]
I believe we should not alter the bash  syntax. but instead only replace variables that are inside env 
${HELLO} will be processed only if process.env.HELLO exists 

and ${REDIS_HOST:-localhost} is definitely not a JS syntax 

And if it really became a problem I would rather promote JS template strings to be just JS code to avoid ${} syntax at all 
like here http://www.express-gateway.io/docs/policies/expression

**Comment by DrMegavolt** [comment]
closing this in favor of #510
