### ISSUE TITLE
Plugin Framework: refactor OAuth2 server as EG plugin based on spec

### ISSUE THREAD

**Issue by jimhw** [ExpressGateway/express-gateway#45]
Create policy to handle different OAuth2 strategy

**Comment by Tiberriver256** [comment]
@DrMegavolt: would it be possible to expand a bit on what you were thinking for this:
```
Wrap oauth2 into plugin type, so it will not spin its own server
```
Are you planning on just doing like a passport-oauth2 that would point at another stand-alone OAuth server?
