### ISSUE TITLE
Bug: Not honoring EB_CONFIG_DIR override

### ISSUE THREAD

**Issue by thedonvaughn** [ExpressGateway/express-gateway#471]
If I try to change my config dir using the EB_CONFIG_DIR environment variable override, it is not honored.

I have a config for local development and for production deployment.

If I issue `EB_CONFIG_DIR=local/config npm start`  - express-gateway ignores that and still loads the default config/ dir.

**Comment by kevinswiber** [comment]
Hey @thedonvaughn, try using `EG_CONFIG_DIR`.  Note the `G` instead of the `B`.

**Comment by altsang** [comment]
@thedonvaughn - hopefully fixed your issue? going to close this for now
