### ISSUE TITLE
minor documentation typo for apiEndpoints

### ISSUE THREAD

**Issue by Vandivier** [ExpressGateway/express-gateway#474]
http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints

"API consumers may API requests through the API endpoints."

Should read

"API consumers may make API requests through the API endpoints."

**Comment by altsang** [comment]
thx @vandivier, will take care of it

**Comment by XVincentX** [comment]
Closed in [165 - eg.io](https://github.com/ExpressGateway/express-gateway.io/pull/165)
