### ISSUE TITLE
Put the Amin API under test using dredd

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#480]
Although the ADMIN Api is shipped with a Swagger document, we don't test that the document is in synch with the current implementation and it's also outdated.
[dredd](http://dredd.readthedocs.io/en/latest/) could make that happen, and I do think we should do it.

**Comment by XVincentX** [comment]
`Dredd` does not support OpenAPI 3.0 (yet). This might be blocked till that moment.

**Comment by DrMegavolt** [comment]
closing this for now. who knows what the good tool for this will be in 1 year

**Comment by XVincentX** [comment]
Dredd will be the tool, trust me.

I'm not sure where should I track these things if we are going to close the issues in this way, though.
I'll probably have to keep a separate list somewhere 👎
