### ISSUE TITLE
JSON Schema Validation: Iteration 2

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#484]
We do now have basic schema validation for entities loaded during the startup/reload.

What's missing though:

3. [x] We should come up with a decent `$id` for each schema
4. [x] Show a warning when a policy/plugin/condition/whatever schema is not provided. People should know it.
8. [x] Clarify what should happen when an object is not respecting the schema.
2. [x] We have multiple parts that are still missing the schema — and some of them might be even reused across different parts of the gateway
10. [x] Go around the whole gateway and check if there are some checks or default that could be brought outside from the code in favor of the schema.
6. [x] Update typescript Json schema definition
5. [x] Update the rewrite plugin schema to leverage the new version. [Repo issue](https://github.com/ExpressGateway/express-gateway-plugin-rewrite/issues/4)

**Comment by XVincentX** [comment]
@kevinswiber @altsang @DrMegavolt 

We need to decide what we want to do when a policy or condition is failing its schema validation.

We can:

1. Warn the user that the validation failed, and threat the policy/condition under process as a no-operation

2. Send an error message and throw an exception, preventing the gateway to start. 

3. Skip the entire pipeline where the policy is being loaded (to be explored more, though)

4. Other ideas you'll suggest

I'd go with the number 2, for a number of reasons:

* JSON Schema support default values, therefore it is possible to achieve a zero-configuration policy/condition *AND* have a schema
* When writing a plugin or anyway a new condition/policy, you can avoid defining a schema. We shouldn't do that, but if somebody is really lazy, it's still possible to do so
* More importantly, a skipped condition/policy could potentially lead to strange behaviors as well as security leaks.

Let's say, for example, I configure a JWT policy in order to validate tokens with a certain token files, and I make a typo in the configuration: `zecret` instead of `secret`.

The validation would fail and the policy would be a no-op: the resource is now unprotected, and the gateway, although would complain with a warning, would still run correctly.

On the other hand, throwing an error and preventing the gateway to start would basically force the user to look into, and fix the mismatch as soon as possible. In meantime, we're not even running therefore we're in a safe zone.

By the way, the current behavior is n. 2 already, but the error message is unpleasant.

**Comment by altsang** [comment]
I think option 2 is fine. But that means you can’t live install a plugin later as a future feature without abruptly stopping to server? We can handle it more gracefully if and when we get there I suppose

**Comment by XVincentX** [comment]
Ok, I've been proceeding here for a while (branch [here](https://github.com/ExpressGateway/express-gateway/compare/feat/json-schema-2-1?expand=1))

There are couple of questions/clarifications needed here:

* In order to make the Admin API and the CLI leverage the JSON Schemas, we need to migrate the models from code to JSON Schema, so the Gateway can validate the data *AND* offer an autocomplete CLI experience (required parameters and stuff like that). This is kind of a big deal I guess, so I want to make sure all of you guys are aware of the change before proceeding.

* I noticed what could be an annoying thing here. At the moment we can detect that a policy is failing the JSON Schema validation *before* the gateway spins up. So, if the policy is fed with invalid data, we can prevent the gateway to start and notice the user as soon as possible. With conditions, this is not possible at the moment, for couple of technical reason. I don't know the design reasons, but conditions are handled in a slight different way than a normal express middleware so the schema validation is deferred until a real http request is being evaluated. This is bad for two reasons:
  * We're evaluating the JSON schema for every single request, wasting resources.
  * We do not know if a condition is valid unless at least a single request comes in. This is harmful.

I can tame this beast (I already have a stash with a workaround) but almost all the tests are failing and it might require a certain amount of time to make it work properly.


@altsang @kevinswiber 

Could you please revise the point and eventually discuss if it's ok for you guys to proceed in this direction?

**Comment by altsang** [comment]
@XVincentX thanks for the summary - great write up

yes - let's fix this, sounds like there is a bunch of cruft to deal with to get to the original feature, but in the process we'll clean it up, esp with the potential bomb around first request thrown

**Comment by DrMegavolt** [comment]
1) validating conditions before EG start is reasonable. +1 
And I don't believe you need to rewrite EG, just add validation step before entire routing processing.
It will be much easier to cover this logic with tests. It should *not* break any test (unless some typo in config) !! 
- config load
- pipeline load
- config validate  (NEW step to validate conditions and actions )
- process routes and build app
- run 

2) migrating Models to schema +1

**Comment by XVincentX** [comment]
#575 and #574 have been created from this original issue.
