### ISSUE TITLE
JWT Plugin

### ISSUE THREAD

**Issue by renatoramiro** [ExpressGateway/express-gateway#486]
Hello everyone,

I made a simple plugin to check  if jwt token is valid. It can help  someone and can be improved.

It was done using the generic plugin example: [https://github.com/renatoramiro/express-gateway-plugin-jwt](https://github.com/renatoramiro/express-gateway-plugin-jwt).

**Comment by DrMegavolt** [comment]
@renatoramiro  Great work! Thanks for sharing!
 
Getting full featured JWT plugin is one of our key priority. And the way you implemented it is one of the most common usage scenario. 

connect #30 connect #419

**Comment by altsang** [comment]
thanks for the contribution!  we'll be sure to look at it when we release the full blown JWT plugin that supports all other use cases beyond generic JWT
