### ISSUE TITLE
Standardize formatting rules

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#493]
We do have multiple code style in the current codebase — and different editor are treating it in a different way with integrated autoformatters.

Therefore, each pull request contains tons of autoformatting changes that make the code review a pain.

We should give prettier a try and eventually integrate it in our eslint installation.

1. [x] Stop dealing with whitespaces
2. [ ] Introduce `prettier`

**Comment by XVincentX** [comment]
I will hold on with this until we have almost 0 PR to review/merge, or rebasing will be a mess.

**Comment by DrMegavolt** [comment]
after new PR with git pre commit hook. just add `-n` to skip check for this commit

**Comment by dotBits** [comment]
since is available pre-commit hook with "lint", what about to create a list of requirements in order to hook that specific eslint configuration?

**Comment by XVincentX** [comment]
Prettier is not happening. I've been using it for a while in Stoplight and I haven't seen any real value out of it (if not increasing the time to commit something). Definitely not worth it.
