### ISSUE TITLE
Support for Redis-Sentinel

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#499]
Express Gateway can only work with a single Redis instance at the moment. 

*Sentinel* provides high scalability for Redis and it's a mandatory step to go in production when you're storing important data (such as keys and so on and so forth).

We need to implement support for it.

### Battle plan

- Evaluate a new Redis client. The current one does not support Sentinel natively and, although there's a library that [can monkey patch the methods](https://github.com/ortoo/node-redis-sentinel). It's not maintained as well as its usage is discouraged. We should use [ioredis](https://github.com/luin/ioredis) as it is the official solution.

- We're using FakeRedis when the `emulate` flag is true (for testing purposes as well in memory instances). Is this going to work even when the client will be switched? [There's an alternative](https://github.com/nileshmali/ioredis-in-memory)

**Comment by XVincentX** [comment]
## ioredis

- [It's throwing exception when there's no data](https://github.com/stipsan/ioredis-mock/issues/328)
- [It's missing implementation for `scan` command](https://github.com/stipsan/ioredis-mock/blob/master/compat.md), which we're using.

**Comment by DrMegavolt** [comment]
ioredis seems to be the way to go. it is recommended client on the redis page

we should not remove in memory storage. it is crucial for getting started experience. 
and we should not run unit tests against real redis

bugs seems to be non-critical. should be possible to fix

**Comment by DrMegavolt** [comment]
and `*Async` is just a hack to modernize old school library, obviously all `xxxAsync` methods can be renamed to normal looking methods

**Comment by XVincentX** [comment]
This just happened. #537 for followups
