### ISSUE TITLE
auto publish: setup CircleCI to "auto" publish

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#550]

**Comment by DrMegavolt** [comment]
Is this task about auto releasing and npm publish patch releases ?

**Comment by XVincentX** [comment]
CircleCI now publishes Express Gateway automatically on Npm and Docker when a new tag is created.

Once a new release is created, Zapier is propagating the text on Gitter and `discuss@express-gateway.io`. I'd say we reached the one click deployment status. 🔝
