### ISSUE TITLE
JWT Plugin: Integration with Express-Gateway identity features

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#558]
### EG as a token issuer

Express Gateway could can also issue a JWT token using the informations we have in the gateway (such as `consumerId`, `consumerName`, the `scopes` array and so on and so forth). Question is, how do we want to issue such token? One way would be through the `oAuth2` plugin. If so, how should this token look like (in terms of payload)?

**Comment by XVincentX** [comment]
Outstanding questions:

* How the JWT should look like? Source of inspiration?

* What are we going to do with the current Token Service?
  * Kill it completely and use JWT for everything.
  * Keep it temporarily as a legacy service and remove it later  
  * Keep both systems, and let the user decide which one to use, probably introducing AccessTokenType parameter in oAuth2 policy configuration

**Comment by altsang** [comment]
> Outstanding questions:
> 
> How should the JWT look like? Source of inspiration?
> {
>   "iss": "EG",
>   "sub": "consumerId",
>   "sco": ["read", "write", "admin"]
> }

will let @kevinswiber comment
> What are we going to do with the current Token Service? It corresponds to the "Opaque" Token in Auth0.
> 
> Kill it completely and use JWT for everything.
> Keep it temporarily as a legacy service and remove it later
> Keep both systems, and let the user decide which one to use, probably introducing AccessTokenType parameter in oAuth2 policy configuration

the token service should be *the* token service and what tokens it is able to issue - opaque, JWT, etc should be something that the EG auth policy can call into via a parameter - can we consolidate into _one_ "system" and let the user decide via parameter in OAuth2 policy config?

> Given EG has issued the token, should we modify the JWT verifier policy in order to validate the scopes? As we know the token's shape, we know where to find those.

if the JWT policy is configured to be the SOR - yes

> 
> It seems like the oAuth 2 policy is doing more than it should. According to the source code, it is coupling consent/token issuing with token verification (and it's assuming it's going to be a Bearer token). oAuth is all about authorization and exchanging data for a token. Its verification it's not a its concern, and it should be handled by another policy. Ideally one should put the oAuth2 policy just to offer the required endpoints (/authorize /token), and then put a token verification strategy (that can be the simple Bearer one to verify an opaque token, or JWT) @kevinswiber @altsang This might be blocking.

a token verification policy is too granular, this should just be a configuration - remember our OAuth2 policy in conjunction with the credentials management system including the underlying services is a reference implementation for getting started. we made the assumption for bearer, if this is no longer the case because someone wants to override with something else - parameterize it

**Comment by XVincentX** [comment]
> the token service should be *the* token service and what tokens it is able to issue - opaque, JWT, etc should be something that the EG auth policy can call into via a parameter - can we consolidate into _one_ "system" and let the user decide via parameter in OAuth2 policy config?

My bad, I didn't ask the right question. I was talking about the "opaque" token. Do we still want to support it? From your answer it is clear to be a yes. Will do.

> if the JWT policy is configured to be the SOR - yes

Yes boss! 🆗 

> a token verification policy is too granular, this should just be a configuration - remember our OAuth2 policy in conjunction with the credentials management system including the underlying services is a reference implementation for getting started. we made the assumption for bearer, if this is no longer the case because someone wants to override with something else - parameterize it

Ok. I'll figure out how we can reuse the JWT verification configuration part in this oAuth policy.

**Comment by XVincentX** [comment]
## Blocking points

* Policy routes (at the moment `oauth2` policy is the only one that has routes) are loaded ahead of the time, before policies themselves. Therefore, at the current state, there's no way I can get access to the current policy configuration (that I need in order to know whether I should issue JWT tokens or opaque tokens).
