### ISSUE TITLE
Replace validateGatewayConfig with Json Schema

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#561]
[validateGatewayConfig](https://github.com/ExpressGateway/express-gateway/blob/master/lib/gateway/pipelines.js#L190) is an hardcoded function that can be simply replaced with a good Json Schema.

**Comment by DrMegavolt** [comment]
+1

**Comment by XVincentX** [comment]
This, unfortunately, cannot be done. 

That function is indeed manipulating the configuration so that `apiEndpoint` object becomes `apiEndpoints` array and stuff like that. It's basically handling synonyms.

This is not something that JSON Schema can do for us.
