### ISSUE TITLE
Get rid of HMSET command

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#566]
Starting with Redis 4.0.2, [HMSET is now deprecated](https://github.com/antirez/redis/blob/4.0/00-RELEASENOTES#L195) and it should be replaced with `HSET` instead.

No rush, it will be supported for years to come.

**Comment by DrMegavolt** [comment]
I would use HMSET everywhere right now, and as you said will talk about it in 3 years

**Comment by XVincentX** [comment]
Yup!
