### ISSUE TITLE
Replace `uuid-base62` package

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#568]
It's deprecated, we can find better solutions for that hopefully.

**Comment by jingsam** [comment]
How about shortid

**Comment by DrMegavolt** [comment]
2 issues here: 
It is used as uuid generator for key-auth to make generated key friendlier. this should remain base62

and used in tests to make it easier to compare values. doesn't matter what is used here. probably some human readable word generator will work "little-brown-fox"

**Comment by XVincentX** [comment]
uuid (even if base62 encoded) often take into account the timestamp or MAC address of the server generating it. There's a certain degree of predictability intrinsic in these.

The standard to generate a secure secret is to use a cryptographically-secure library to generate a N-bit value and converting it to a hexadecimal representation; we could use [the builtin crypto library](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback) to make this happen in the Gateway.

Once converted into an hex string it should be enough *safe* and *easy to remember/copy paste*

```javascript
const crypto = require('crypto')
const buf = crypto.randomBytes(16);
console.log(buf.toString('hex')); // 7224a5b5bb0efcf45263f7bc84195f02
```
Safe and sound.

What do you guys think? @jingsam @DrMegavolt //cc @kevinswiber 

> and used in tests to make it easier to compare values. doesn't matter what is used here. probably some human readable word generator will work "little-brown-fox"

Yes! Maybe `faker` or a simple `uuid/v4()` can do the job.

**Comment by DrMegavolt** [comment]
this is exactly how it is generated 
https://github.com/kelektiv/node-uuid/blob/master/lib/rng.js#L7

**Comment by DrMegavolt** [comment]
base 62 has nothing to do with generation of id. it is encoding format. 
URL safe alternative to base64

**Comment by XVincentX** [comment]
Oh that's really cool. Thanks for pointing this out.

It's actually part of the `v4` spec!

In that case, it's really just matter of replacing the `uuid-base62` with [uuid62](https://www.npmjs.com/package/uuid62). It has updated dependencies and 100% compatible with the current one.
