### ISSUE TITLE
REST helpers should properly encode query parameters

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#572]
All the admin helpers (used by the CLI) are concatenating url parameters as plain [strings](https://github.com/ExpressGateway/express-gateway/blob/master/admin/users.js#L18)

This means that if I put an user with some URL-unsafe characters, I'll receive a not found message (although the user probably exists) or even an error.

This might be a good occasion to also DRY the admin client as well. A lot of copy paste is happening there.

**Comment by iwko** [comment]
@XVincentX So we need to use some kind of sanitizer?

**Comment by XVincentX** [comment]
Hey!

Yes, the idea would be to construct the target URLs using some well know library to do that; maybe the included `url` module in NodeJS can do the job as well.

Would you like to contribute on this one? If so, I can point you where the changes should be made and make it happen 🚀

**Comment by iwko** [comment]
Cool, I can do it

**Comment by XVincentX** [comment]
Glad to hear that.

A quick dirty way to make that happen would be to use `encodeURIComponent` on the url paths, in particular on the variable parts (such as `id`).

Given you're there, you could also replace the string concatenation with a string template `${}` and then encode. Something like:

`${baseUrl}${encodeURIComponent(id)…}`

In meantime, I'll rework some parts of the base clients so we can better accommodate your changes.

Does that make sense? If you have a different idea, feel free to post it here!

**Comment by XVincentX** [comment]
@iwko I have created a pull request that is putting the things in order on our side for the Http Client. That should not really change the work to close this issue, but it should simplify your process of reasoning on the code a bit. You can use that as a base branch until it gets merged.

If you need anything else, feel free to ping me here or on Gitter.
