### ISSUE TITLE
node-uuid is depreciated

### ISSUE THREAD

**Issue by NonCreature0714** [ExpressGateway/express-gateway#577]
For all other issues:
- [ ] please choose a label: `Question` or `Bug`
- [ ] for `Bug`(s) please include steps to reproduce and any supporting info that might be helpful e.g. `gateway.config.yml`

I don't know enough yet to tag this as a tag or a question, but: 

During install, npm produces the warning:
`npm WARN deprecated node-uuid@1.4.8: Use uuid module instead`

Was node-uuid recently depreciated? Is there already work to switch to uuid?

**Comment by XVincentX** [comment]
Hey,
thanks a lot for the issue.

We're already aware of the thing and it's been tracked here: https://github.com/ExpressGateway/express-gateway/issues/568

You can continue the discussion there. We're in the process of fixing this!
