### ISSUE TITLE
Improve EG on Docker

### ISSUE THREAD

**Issue by DrMegavolt** [ExpressGateway/express-gateway#589]
https://hub.docker.com/r/expressgateway/express-gateway/

has generic readme, but it should contain info how to mount config like here
https://www.express-gateway.io/docs/runtime/#configuration-loading-and-override

**Comment by XVincentX** [comment]
Also, let's try to be part of the "Official images" program

**Comment by DrMegavolt** [comment]
and for some reason it is not searchable with dash 
express-gateway. 
I need expressgateway

**Comment by altsang** [comment]
- investigate being part of official docker image program

**Comment by XVincentX** [comment]
1. Investigate moving building the images from CircleCI scripts (that fails everytime something small changes) to Docker cloud directly
2. Investigate and do the necessary changes so we can be part of the Docker Official Image Program (update image and readme)

**Comment by XVincentX** [comment]
Create a different repository — https://github.com/mongo-express/mongo-express-docker might be a good source of inspiration.

Also — how to automate such thing when we release EG?
