### ISSUE TITLE
Remove coupling between user and apps in EG Consumer Management

### ISSUE THREAD

**Issue by DrMegavolt** [ExpressGateway/express-gateway#605]
Oauth2 flows require users and apps. 

Apps represent some machine like browser 
User is a human who is granting access for app to some resources 

Current implementation assumes that user have multiple apps. 

That is not correct. Those are independent entities. and typically number of apps is less than number of users.

Minimal fix is to make apps independent. And user and apps global (no multi tenancy )

More advanced version is to have user and apps belong to some account\org\tenant 
So I will not be able to use APP-A-1 from orgA from UserB-1 that is registered in tenantB

cc @altsang @kevinswiber @XVincentX ^^

**Comment by altsang** [comment]
this isn't accurate, users are app owners and app consumers, i've created another bug to re-classify this bug
