### ISSUE TITLE
BUG: Getting started template config error

### ISSUE THREAD

**Issue by ronnetzer** [ExpressGateway/express-gateway#614]
[ BUG ] Getting started template has an error in gateway.config.yml

data.apiEndpoints['api'].paths should be array and currently isn't.

**Comment by MahdiMahava** [comment]
The same issue

**Comment by FazioNico** [comment]
same issue... 😔

**Comment by XVincentX** [comment]
Thanks a lot for the report!

There's a bug indeed. The schema is not correct, as `paths` can be both an array or a simple string.

#615 will fix the issue, and we'll likely release it as a bugfix for 1.6.1

In meantime, you can easily fix the thing by modifying the current `gateway.config.yml`:

```diff
-    paths: '/ip'
+    paths:
+      - '/ip'

**Comment by XVincentX** [comment]
@MahdiMahava @FazioNico @ronnetzer 
This issue should now be solved with 1.6.1

Could you please try to upgrade the installation and let me know if it's now working correctly?
