### ISSUE TITLE
Oauth2 related configs are required in system.config even if it is not in use 

### ISSUE THREAD

**Issue by DrMegavolt** [ExpressGateway/express-gateway#616]
props like `crypto` `session` etc. are required after JSON schema validation was introduced. 
previously it was possible to use EG  with just `db` section set to emulate

**Comment by XVincentX** [comment]
This might be tricky. If we remove such constraint, then we might incur in the opposite problem: somebody uses the oAuth2 policy and it does not work because they are not providing the relative sections.

@kevinswiber We might need to discuss this.

**Comment by DrMegavolt** [comment]
yes, the for example `crypto` object has all it needs, but there is no default for the object itself.
