### ISSUE TITLE
invalid pipeline config should not crash EG and should still allow for correction via admin API

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#646]

**Comment by altsang** [comment]
Expected behavior: 
a gateway’s pipeline(s) may be invalid however, EG should still be running and expose the admin API to fix the invalid config

Actions to take:
- modify the Gateway so that there is resiliency so that an invalid config does not crash the gateway
- also add status of the pipeline as crashing/valid

**Comment by XVincentX** [comment]
Commented privately.

**Comment by altsang** [comment]
closing for now - may not applicable anymore
