### ISSUE TITLE
Clustering: spec on what data and config is kept across cluster

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#649]

**Comment by sicrossley** [comment]
I'd be very keen to understand your thoughts about global counters. I'd like to use EG in load balanced cluster, with a rate limiting policy. I may be able to help with a contribution depending on the size of the change that you're planning.

**Comment by altsang** [comment]
Simon - pleased to report that this is already done, was in a release not
to long ago. Global counters are stored in the namespace that is shared
among all EG instances.

-a-


On February 27, 2019 at 3:31:30 PM, Simon Crossley (notifications@github.com)
wrote:

I'd be very keen to understand your thoughts about global counters. I'd
like to use EG in load balanced cluster, with a rate limiting policy. I may
be able to help with a contribution depending on the size of the change
that you're planning.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ExpressGateway/express-gateway/issues/649#issuecomment-468073396>,
or mute the thread
