### ISSUE TITLE
OpenAPI: spec on how OpenAPI is ingested and gateway is scaffolded

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#650]

**Comment by XVincentX** [comment]
I've been going through the whole [OpenAPI 3.0.1](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md) and here's what I see as touching points with Express Gateway

# server object

The `server` object contains the base URL for an API exposed. It is used most of the times in an array specifying multiple servers.

```yaml
servers:
- url: https://development.gigantic-server.com/v1
  description: Development server
- url: https://staging.gigantic-server.com/v1
  description: Staging server
- url: https://api.gigantic-server.com/v1
  description: Production server
```

## Integration point

This would be the `host` which Express Gateway is listening requests

# path object

The `path` object represents a path of an API.

```yaml
/pets:
  get:
tags:
- pet
summary: Updates a pet in the store with form data
operationId: updatePetWithForm
parameters:
- name: petId
  in: path
  description: ID of pet that needs to be updated
  required: true
  schema:
    type: string
requestBody:
  content:
    'application/x-www-form-urlencoded':
      schema:
       properties:
          name: 
            description: Updated name of the pet
            type: string
          status:
            description: Updated status of the pet
            type: string
       required:
         - status
responses:
  '200':
    description: Pet updated.
    content: 
      'application/json': {}
      'application/xml': {}
  '405':
    description: Invalid input
    content: 
      'application/json': {}
      'application/xml': {}
security:
- petstore_auth:
  - write:pets
  - read:pets
```

## Integration point

- `requestBody`'s schema could be validated by Express Gateway and refuse the request if the validation fails. This would require us to craft a new policy `schema-validator` that could leverage the internal schema system we already have in place.

- The `security` section could be done placing the right policy in place before proxying the request. The spec specifies `apiKey http oauth2 openIdConnect`.  We do not support `openID` and the `apiKey` method specifies some ways we do not support currently: `query`, `header` or `cookie`. We're on `header` only.

## Questions

**Comment by XVincentX** [comment]
https://docs.google.com/document/d/12OsuoxjrFqJeNQbxkCeSLLrIR6PG6QMyHHrIkAHk1fc/edit?usp=sharing

**Comment by XVincentX** [comment]
I've updated the document with couple of more notes, I think somebody else should start having a look into and put comments into.

**Comment by XVincentX** [comment]
I'll close this. The scaffolding has been done and it's public.
