### ISSUE TITLE
can not create user via cli

### ISSUE THREAD

**Issue by MillerRen** [ExpressGateway/express-gateway#669]
eg users create
? Enter firstname [required]: kate
? Enter lastname [required]: kate
? Enter username [required]: smith
? Enter email: undefined
? Enter redirectUri: undefined
✖ <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST //users/</pre>
</body>
</html>

`//users/` is not a valid path

**Comment by XVincentX** [comment]
Hey — this is a bit weird, the thing seem to work correctly here. Could you provide all the stesp to reproduce this?

**Comment by jinasonlin** [comment]
I also encountered this problem. 

https://github.com/ExpressGateway/express-gateway/blob/master/bin/eg-generator.js#L80
https://github.com/ExpressGateway/express-gateway/blob/master/admin/users.js#L2

Final request address is `http://localhost:9876//user/`, not `http://localhost:9876/user/`

Temporary resolution：
`EG_ADMIN_URL=http://localhost:9876 eg users create`
or
config `systemConfig.cli.url`

**Comment by XVincentX** [comment]
Thanks for the reproduction steps! I'm going to have a look into!

**Comment by XVincentX** [comment]
@jinasonlin  @MillerRen 

I've tried again and I haven't been able to replicate the issue.

![image](https://user-images.githubusercontent.com/1416224/37596041-dfb5c11e-2b48-11e8-81dd-7bf6562f6678.png)

Can you tell me the EG Version installed on your computer as well as your operating system? Maybe it's something Windows specific!

**Comment by jinasonlin** [comment]
@XVincentX You can try without `EG_ADMIN_URL=http://localhost:9876`.  Just directly run `eg users create`.

**Comment by XVincentX** [comment]
@jinasonlin Same. I really need more details on your configuration (such as EG version and operating system)

**Comment by jinasonlin** [comment]
<img width="394" alt="2018-03-19 10 33 26" src="https://user-images.githubusercontent.com/5010606/37601707-b44a84ce-2bc5-11e8-88f6-d3b1212a7b5c.png">
<img width="405" alt="2018-03-19 10 33 33" src="https://user-images.githubusercontent.com/5010606/37601708-b5712240-2bc5-11e8-8b86-9a1ab83664d8.png">
<img width="440" alt="2018-03-19 10 37 00" src="https://user-images.githubusercontent.com/5010606/37601875-1875172a-2bc6-11e8-9225-908a89688619.png">


You can use cli to create a project, and run it. In the same dir, will reproduce this issue?

**Comment by XVincentX** [comment]
@jinasonlin Reproduced. I'll have a look into, thanks a lot for this one!

**Comment by XVincentX** [comment]
This bug seems to be caused by the poor way that `superagent` is handling the urls. This might be an annoyance to deal with. Maybe switching with `axios` could be the solution?

**Comment by XVincentX** [comment]
I've released EG 1.7.4 as an hotfix for that.

**Comment by MillerRen** [comment]
:+1: @XVincentX thx
