### ISSUE TITLE
oauth2 expiry time is not present

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#679]
per Davendra, - needs to be verified as a bug

**Comment by XVincentX** [comment]
The spec states the `Client Credentials` grant type *MUST NOT* allow for the issuing of refresh tokens. 

So the answer is, you have to use a different grant type to receive a refresh token with your access token.

I can verify all the flows but I think we're doing the right thing.

**Comment by altsang** [comment]
got it - can we double check flows and can we also make sure there is an `expiry date` present for access tokens? he mentioned that there was no attribute found on the access token? maybe this is by design?

**Comment by XVincentX** [comment]
That might be effectively a bug. I can dig into — let's plan for it in person.

**Comment by XVincentX** [comment]
@altsang: from the spec:

```
 expires_in
         RECOMMENDED.  The lifetime in seconds of the access token.  For
         example, the value "3600" denotes that the access token will
         expire in one hour from the time the response was generated.
         If omitted, the authorization server SHOULD provide the
         expiration time via other means or document the default value.
```

So — theoretically we're not wrong here, but rather "implicit". I will add the value to all the responses so we're explicit about it. Does that make sense?
