### ISSUE TITLE
Drop NodeJS 6 support?

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#688]
NodeJS goes in maintenance LTS on `2018-04-30`.

Dropping its support, we can cleanup the codebase a bit and remove some specific hacks.

**Comment by DrMegavolt** [comment]
This should not happen, it is not about LTS or not. it is about version usage. 
https://nodesource.com/node-by-numbers
Node6 has a significant usage (more than 8)
@altsang ^^

**Comment by XVincentX** [comment]
I didn't know the website. It's a cool one! Anyway…

Speaking about the numbers, your analysis is not completely correct.

Even at peak numbers, you should not consider one version per time, but more Node 6 vs (Node 7-8-9). In that case I think the game changes a bit (but I haven't been able to make the computations yet)

Furthermore, Express Gateway is not a library, so you do not really have such compatibility problem. Plus, if you're on the Docker Image, you do not care at all.

Last thing — it does not have to happen today or tomorrow or exactly at 04/30 — but I think it's worth raising the issue so we know what's the plan (maybe the issue title was not the best one in the world, that's my fault). Let's leave it open just to discuss the intensions with _tha boss_ and we'll close it if it's the case.

**Comment by DrMegavolt** [comment]
you labeled it as 1.9. It cannot happen as 1.9; this is major 2.x

And it should have a reason for that. not just cleaner code. Anything that is on the list today is doable with the same amount of efforts in node6. 

>Furthermore, Express Gateway is not a library, so you do not really have such compatibility problem

In larger organizations, EG customers may have to get approval for a new stack. And this process typically takes a while.  So this is yet another bump to adoption.  
And chances to get approval for 7.x or 9.x are pretty low, they are for devs, not prod. So comparison should be 6 vs (8 + 10) 

@altsang @kevinswiber @XVincentX  I propose to close it to not pollute backlog and revisit in 1 year

**Comment by XVincentX** [comment]
> you labeled it as 1.9. It cannot happen as 1.9; this is major 2.x

Oops! That was an unintended mistake — definitely not for 1.9.

> And chances to get approval for 7.x or 9.x are pretty low, they are for devs, not prod

That is also correct.

I recall @kevinswiber was progressive on this point as well. I'm fine, if everybody is on the same page, to revisit this in a while.

**Comment by kevinswiber** [comment]
I'm less conservative than @DrMegavolt on this.  However, I will state that Express Gateway _is_ a library.  If anyone is using the gateway generator to scaffold a project, they're using Express Gateway as a library.

Happy to make this a candidate for v2.0.  However, I'm not sure we're actively planning a v2.0 release at this time.  Therefore, I agree with closing it for now.

**Comment by XVincentX** [comment]
Let's revisit in a while then.
