### ISSUE TITLE
Admin API: Apps / Users improvements

### ISSUE THREAD

**Issue by kevinswiber** [ExpressGateway/express-gateway#689]
- Return username in apps
- Fix `nextKey` format to be always numeric.
- Return accurate counts on API response.
- Allow setting `count` on API request.

**Comment by XVincentX** [comment]
Personal notes:

1. Return username on Admin API apps routes. Now it's just the `userId`
2. It seems like `nextKey` sometimes is not numeric, but completely wrong. Investigate.
3. Make sure people can define how many users/apps return from a general call through a query parameter.
