### ISSUE TITLE
Admin API: return back all credentials

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#702]

**Comment by XVincentX** [comment]
@altsang 

Shall it return all credentials regardless of the status? (Active, deactivated)?

Or add a query parameter to to select whether you want them or not? If so, what would be the default value?

**Comment by altsang** [comment]
Return active by default, unless overridden with parameter for filter -
active, deactivated

There is already some other filtering at the url path level for consumer
and type?

**Comment by XVincentX** [comment]
I realized we do not have any filtering capability on the server side. These features are offered because of the CLI. Let's stick with that for now, we can reiterate on that when needed.

**Comment by XVincentX** [comment]
Escalated in points because of a weird behavior in our test suite. :(
