### ISSUE TITLE
Consider the idea of removing bcrypt native module

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#724]
I was wondering whether wouldn't it be better to simply drop `bcrypt` and have `bcryptjs` only. It is not a speed-critical part of the system (user creation) and it would remove a lot of hassle here.

**Comment by DrMegavolt** [comment]
I'm fine with js only version

**Comment by XVincentX** [comment]
@kevinswiber If you agree, we can move this forward and free ourselves from this pain.

**Comment by XVincentX** [comment]
This happened.
