### ISSUE TITLE
How I can proxy websocket request by different websocket event? 

### ISSUE THREAD

**Issue by devfat** [ExpressGateway/express-gateway#735]
How I can proxy websocket request by different websocket event? 
( like in socket.io, socket.emit(event, data))

**Comment by XVincentX** [comment]
Discussed in person in Gitter.

**Comment by dadiborn** [comment]
"Discussed in person in Gitter."
The worst answer ever. Maybe it is possible to provide a link? Have you ever tried to find something in Gitter?

**Comment by XVincentX** [comment]
Hey,

I understand your frustration — I've been on the other side of the project as well; it definitely happened to me as well that I was looking for some info, and it was stored elsewhere. I apologize for that; with the high number of support request I get, I need to drain the time somewhere to help all of you.

In cany case, to keep it short, we’re still in the planning phase for a serious websocket support: we're waiting on hearing more about websocket support to understand the use case.

Once we’ll gather enough requirements we will start to put some code and see where it will lead us. Which brings me to the question: what are you looking for in particular from the Websocket support?

**Comment by dadiborn** [comment]
Thanks for reply, I just wrote in GITTER thet you need to MARK in RED that thing with WEBSOCKET situation, that will helps and people will be not waste their time

**Comment by dadiborn** [comment]
"Which brings me to the question: what are you looking for in particular from the Websocket support?"
I will answer in a different way on this.
When we see HUGE demonstrations of framework, tool or service features, and as addition official comparisons with others (like EG did with KONG and TYK), I think basics should match before we can compare, and if WebSocket is not a part of EG basics, thats sad, as WS is part of our life for a long time already. But that is just my opinion, im not an expert like you :)
