### ISSUE TITLE
Consent page improvements: minimal style + scope show

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#739]
The consent page we're offering right now is really spartane.

Let's add some minimal style and, more importantly, let's clearly show to the user the scopes that the current application is requesting.

**Comment by XVincentX** [comment]
@ravikp7 Is this something you're willing to complete or shall I take over?

**Comment by ravikp7** [comment]
Hey @XVincentX 
Thanks for the heads-up. I'll be working on it today. And, will keep you updated
