### ISSUE TITLE
Question - Swagger Documentation for MicroServices

### ISSUE THREAD

**Issue by arpit-systango** [ExpressGateway/express-gateway#743]
We are using express-gateway for our microservices based product and so far we are very impressed with what we have been able to achieve using it. We had a question regarding swagger integration in the api gateway, we understand that we do have an admin application for this gateway and that it has api-docs url for looking at swagger docs, however it only shows us the APIs which are useful in the context of gateway management such as user creation etc. What we are looking for is a way to show the swagger documentation of the microservices those are being called by the gateway. The microservices are written in python-django framework and have swagger docs applied to each api.

Please suggest if this is feasible and how to enable this setting?

**Comment by XVincentX** [comment]
Hey,

that is correct! We provide a Swagger file for the Gateway's Admin API (which unfortunately is outdated a bit — we'll make it work again once we'll be able to solve #480).

That said, there are multiple ways to achieve what you want. If each of your services is exposing such file, then you can simply access the file as any other resource of your service. The gateway would proxy the request and get the result back with no particular problem.

I'd need you to provide some more details but — as this is a question, would it be possible to throw it on StackOverflow with the `express-gateway` tag or jump in our Gitter channel for a real time discussion on the topic?

Thanks!

**Comment by arpit-systango** [comment]
Thanks for your prompt reply Vincent. We will try the alternative you have suggested to treat the swagger as yet another resource and access it via gateway rather than trying to import it in gateway by a hack.
