### ISSUE TITLE
refresh token is not being returned by EG with JWT token type on oauth2 flow

### ISSUE THREAD

**Issue by cesarsosa** [ExpressGateway/express-gateway#744]
When using the JWT token type, using the oauth2 flow on password grant for authenticating the user, the refresh token is not being returned by EG. Is working correctly with opaque token type.

So basically, the grant_type with refresh_token will never work with JWT token type.

**Comment by XVincentX** [comment]
Confirmed as a bug, thanks for reporting it. Refresh tokens aren't generated for JWTs.

**Comment by cesarsosa** [comment]
Any idea of when is going to be resolved?

**Comment by XVincentX** [comment]
I can't give you an ETA on that unfortunately, it depends from a lot of factors. Again, if you're in hurry, LunchBadger provides support plan.
