### ISSUE TITLE
schemas and tokens endpoints are missing from the swagger-docs for admin API

### ISSUE THREAD

**Issue by Tiberriver256** [ExpressGateway/express-gateway#751]
Admin routes can be found here:
https://github.com/ExpressGateway/express-gateway/blob/c24a8f30df2cec5a470d46d238170b4b6a8d5da3/lib/rest/index.js#L29-L38

Swagger-docs is here:
https://github.com/ExpressGateway/express-gateway/blob/master/lib/rest/swagger-doc.yaml

No documentation in the swagger file for either the schemas route or the tokens route.

**Comment by XVincentX** [comment]
Correct! This is a duplicate of expressgateway/express-gateway.io#169

**Comment by Tiberriver256** [comment]
Ah missed that, sorry.
