### ISSUE TITLE
Incompatible depencency upath with Node v10

### ISSUE THREAD

**Issue by CWThomson** [ExpressGateway/express-gateway#752]
Express Gateway appears to have a dependency on upath@1.0.4. This seems incompatible with Node v10.

```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
```

This dependency looks to be imported via chokidar

There is a workaround mentioned in the below issue on another project but ideally some dependencies would be upgraded to resolve this.

https://github.com/facebook/create-react-app/issues/4367

```yarn config set ignore-engines true```

**Comment by XVincentX** [comment]
Thanks for the report! We regularly update all the possible dependencies every time we bump up a minor release, so hopefully this should be just matter of short time.

Thanks!
