### ISSUE TITLE
[Bug] Issues with `eg credentials info` and `eg credentials list` and JWT creds + Redis

### ISSUE THREAD

**Issue by juliusecker** [ExpressGateway/express-gateway#759]
[Bug] 
- Version 1.9.1
- Containerized Redis

#### User & Credential creation
- Startup eg with Redis enabled
- Run `eg user create -p "username=system" -p "firstname=system" -p "lastname=system"`
  - Returns user rec with id, assume its exported in bash as ${eg_id}
- Run `eg credentials create -c system -t jwt`
  - Returns credential

If you check Redis at this point, you can see all of the records that were created including the JWT creds.

#### info and list fail when type is jwt 
- Run `eg credentials info system -t jwt`
  - Expected: credential
  - Returned: Empty response
- Run `eg credentials list -c system`
  - Expected: List with one entry
  - Returned: Empty response

#### info and list fail when using user id and type is jwt
- Run `eg credentials info ${eg_id} -t jwt`
  - Expected: credential
  - Returned: Empty response
- Run `eg credentials list -c ${eg_id}`
  - Expected: List with one entry
  - Returned: Empty response

I also tested this using the ID when creating the credential. No change from the observed behavior above.

I also tested this with type oauth2. List works. Info works if you use the id. Fails when you use the username.

**Comment by XVincentX** [comment]
This needs to be verified. Thanks for pointing this out though!

**Comment by naprime** [comment]
Please fix this issue soon.
