### ISSUE TITLE
Schema isn't being recognised

### ISSUE THREAD

**Issue by markwylde** [ExpressGateway/express-gateway#765]
I'm trying to create a plugin and so far it's working great apart from the schema part.

I have the following `manifest.js` file:
```javascript
module.exports = {
  version: '1.0.0',
  init: function (pluginContext) {
    pluginContext.registerPolicy(require('./policies/blacklist.js'))
  }
}
```

And the following `policies/blacklist.js` file:
```javascript
module.exports = {
  name: 'blacklist',

  schema: {
    $id: 'http://express-gateway.io/schemas/policy/blacklist.json',
    type: 'object',
    required: ['urls'],
    properties: {
      urls: {
        type: 'array',
        items: {
          properties: {
            method: {
              type: 'string'
            },
            path: {
              type: ['string', 'null']
            }
          }
        }
      }
    }
  },

  policy: (actionParams) => {
...
```

The policy works as expected but it's not validating the schema.

I get the following output from my console:

```bash
[EG:config] info: Registered schema for users model.
[EG:config] info: Registered schema for credentials model.
[EG:config] info: Registered schema for applications model.
[EG:config] debug: ConfigPath:
[EG:config] debug: ConfigPath:
[EG:plugins] debug: Loading plugins. Plugin engine version:
[EG:plugins] debug: Loading plugin
[EG:gateway] warn: express-gateway-plugin-bts-blacklist plugin hasn't provided a schema. Validation for this plugin will be skipped.
[EG:plugins] info: Loaded plugin
[EG:gateway] debug: registering policy
```

Note the specific part:

```bash
[EG:gateway] warn: express-gateway-plugin-bts-blacklist plugin hasn't provided a schema. Validation for this plugin will be skipped.
```

I am confused as I have specified the schema. It's just ignoring it.

I'm using Express Gateway 1.10.1.

**Comment by XVincentX** [comment]
@markwylde You're definitely right, the message is confusing.

Express Gateway plugins support schema on 3 levels:

- Plugin level
- Policy level
- Condition level

What's happening in your case is that Express Gateway detected the plugin, but the schema hasn't been provided. This is something that's not really used (we might want to remove it).

To get rid of the warning, simply add an empty schema property at plugin level:

```javascript
module.exports = {
  version: "1.0.0",
  init: function(pluginContext) {
    pluginContext.registerPolicy(require("./policies/blacklist.js"));
  },
  schema: {
    $id: "http://express-gateway.io/schemas/plugins/blacklist.json"
  }
};
```

I'm going to change the message so it's cleaner hopefully soon.

Feel free to reopen in case you need more clarifications.

**Comment by markwylde** [comment]
Thank you for your fast response @XVincentX and your hard work producing this product.

Sorry to reopen the issue but the isn't isn't just with the warning message. It's actually not validating the actionParams against the schema.

I have the following pipeline in my `gateway.config.yml` file:

```yaml
authui:
  apiEndpoints:
    - authui
  policies:
    - blacklist:
        action:
          urls:
            - path: /admin/*
              methodx: get
```

Note that `methodx` should actually be `method` as according to the schema in my original post.

When I run my app it doesn't tell me the actionParams are invalid. I would presume having the schema would alert you if you use a plugin incorrectly?

However, I can confirm that your fix did suppress the warning.

**Comment by XVincentX** [comment]
Hey @markwylde 

this is not an Express Gateway issue. By default, the JSON Schema are permissive — which means that **foreign** properties are allowed.

You can fix this in two ways:

- Make the `method` element required, so if you spell it incorrectly, you get an error:

```javascript
{
    $id: 'http://express-gateway.io/schemas/policy/blacklist.json',
    type: 'object',
    required: ['urls'],
    properties: {
      urls: {
        type: 'array',
        items: {
          required: ['method'],
          properties: {
            method: {
              type: 'string'
            },
            path: {
              type: ['string', 'null']
            }
          }
        }
      }
    }
  }
```

- Set the `additionalProperties` to `false`, so that provided objects *MUST* have only the declared properties:

```javascript
{
    $id: 'http://express-gateway.io/schemas/policy/blacklist.json',
    type: 'object',
    required: ['urls'],
    properties: {
      urls: {
        type: 'array',
        items: {
          additionalProperties: false,
          properties: {
            method: {
              type: 'string'
            },
            path: {
              type: ['string', 'null']
            }
          }
        }
      }
    }
  }
```

Note: the second one, if I recall correctlu is an `ajv` specific feature.

**Comment by markwylde** [comment]
Thanks for your help @XVincentX. I feel a bit stupid now :P

Can confirm everything is working perfectly now!

**Comment by XVincentX** [comment]
This is fine, it happens to everybody. In case you need any further help you can jump in our [Gitter Channel](https://gitter.im/ExpressGateway/express-gateway) too.
