### ISSUE TITLE
Question : Express-gateway deployment into bluemix

### ISSUE THREAD

**Issue by pswamikr** [ExpressGateway/express-gateway#776]
Express-gateway deployment into bluemix 

I'm trying to push a sample express-gateway as an application into bluemix. Stuck with 

config yaml 

https:
  port: ${PORT}
apiEndpoints:
  api:
    host: ${HOST}
    paths: '/ip'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

Getting "Unknown variable: HOST. Returning null."

**Comment by XVincentX** [comment]
Hey,

the error message is clear here — you're missing the `HOST` environment variable set in your host.
