### ISSUE TITLE
Add label TTL in oauth2-infrospect schemas

### ISSUE THREAD

**Issue by kolbinski** [ExpressGateway/express-gateway#783]
As we want to render this property as `TTL`, please add for `http://express-gateway.io/schemas/policies/oauth2-introspect.json` extra `label` field:
```
"ttl": {
  "type": "integer",
  "default": 60,
  "label": "TTL"
},
```

**Comment by XVincentX** [comment]
`label` does not seem to be a JSON Schema valid property. Would it be ok for you to use the `title` property for that? @kolbinski

**Comment by kolbinski** [comment]
@XVincentX `title` is fine. +1 for putting correct titles everywhere. It would be also extremely useful to add `description` for each property (may be the same text as on eg docs), so LB app could also render them.
