### ISSUE TITLE
Rancher Catalog: add EG as helm chart(?) inside Rancher Catalog

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#784]
Rancher has a catalog that is built into its docker image.  When you click on the tile it deploys the vendor's application (through Helm) into the instance of Kubernetes running inside that docker image.

**Comment by XVincentX** [comment]
https://github.com/helm/charts/pull/7130

P.S: Express Gateway is not really Kubernetes/Helm friendly.

**Comment by kevinswiber** [comment]
> P.S: Express Gateway is not really Kubernetes/Helm friendly.

Can you qualify this statement?

**Comment by XVincentX** [comment]
@kevinswiber @altsang 

Sure. There were two points in particular that were making the experience a little bit flaky:

1. You can't update TLS certificates for the Http Server live. You need to update the related config map manually and restart the gateway. This is tracked in #685. Let's say I update the TLS definitions by changing the config map. Unfortunately there's the following point:

2. If you update the config map manually and redeploy it — the hot reload mechanism is not triggered. I guess this is a [Kubernetes Bug](https://github.com/kubernetes/kubernetes/issues/50345) but basically this is forcing me to redeploy the entire chart — `helm upgrade .` does not work.

**Comment by XVincentX** [comment]
PR has been merged as a stable chart, so I'm calling this done.

**Comment by XVincentX** [comment]
![image](https://user-images.githubusercontent.com/1416224/44266582-59483d00-a22b-11e8-9203-30e0bf8b2d50.png)
