### ISSUE TITLE
true up different methods for deployment

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#785]
It's been a while since we updated the possible way to get EG up and running:

- [x] docker
- [x] plain npm
- [x] helm (Rancher Catalog)
- [x] helm (Kubernetes in general)
- [x] swarm (docker)

**Comment by XVincentX** [comment]
@altsang Maybe we should move this to Express Gateway.io repository. There's nothing we can do about these here apart updating the various automation tasks — which is tracked in #772.

Can I close/move the issue in the other repo?

**Comment by altsang** [comment]
@XVincentX go for it
