### ISSUE TITLE
Schemas: missing description for some properties

### ISSUE THREAD

**Issue by kolbinski** [ExpressGateway/express-gateway#817]
Most of the parameters have description in the schemas, except those:
- basic-auth / passThrough
- key-auth / passThrough
- oauth2 / passThrough
- oauth2-introspect - passThrough
- rate-limit / rateLimitBy

**Comment by XVincentX** [comment]
Why's that blocked?

**Comment by kolbinski** [comment]
@kevinswiber @XVincentX I think we had a misunderstanding here:
- yes, UI doesn't support allOf in schemas (card 820 reported)
- no, nothing will break, when EG schemas will be updated with allOf with this PR
That is because schemas are hardcoded in UI and synced manually, they are not taken "live" from schemas endpoint.
Actually, for me to be able work on 820, I need an actual example of schemas with allOf. So "go" from me with this PR.
