### ISSUE TITLE
proxy.js for websocket

### ISSUE THREAD

**Issue by zzzONzzz** [ExpressGateway/express-gateway#827]
proxy.web(req, res, { target, headers, buffer: req.egContext.requestStream });

maybe modify

if (req.headers.upgrade && req.headers.upgrade == "websocket") {
      if (params.ws == true) {
        proxy.ws(req, req.socket, { target, headers, buffer: req.egContext.requestStream });
      }
      else {
        res.end();
      }
    }
    else {
      proxy.web(req, res, { target, headers, buffer: req.egContext.requestStream });
    }

**Comment by XVincentX** [comment]
I wish that'd be so easy.

Unfortunately adding proxy support is something we'd need to do on server level — and it's a little bit difficult to make it happen on endpoint level. We'll get there, but we need to plan this accordingly.

Closing for now.
