### ISSUE TITLE
No log when no apiendpoint matched

### ISSUE THREAD

**Issue by albertlinga** [ExpressGateway/express-gateway#828]
When the request didn't match any apiendpoint, express gateway returns 404. However there's no log that clearly states the reason for the 404 was the no match. 404 can also happen when you have a matching api endpoint but your serviceendpoint has no such path or route. That scenario can be logged via having log policy in the pipeline. It's probably the only case were we get a 404 without any logs but it would have been nice if it explicitly says it's the cause of such result.

**Comment by XVincentX** [comment]
Fair point! I think we can add a small log line before returning the status code to the client as a warning.
