### ISSUE TITLE
Typescript types out of date

### ISSUE THREAD

**Issue by Tiberriver256** [ExpressGateway/express-gateway#830]
PluginContext is missing definitions for these additional properties:

- logger
- services
- settings
- config
- policies
- conditions
- gatewayRoutes
- adminRoutes
- cliExtensions

### Javascript Constructor

https://github.com/ExpressGateway/express-gateway/blob/7094f408d0f460ac9cd03d8c45b7f81f1dbf75a4/lib/plugins.js#L66-L75

### Typescript Definition

https://github.com/ExpressGateway/express-gateway/blob/7094f408d0f460ac9cd03d8c45b7f81f1dbf75a4/index.d.ts#L25-L32

**Comment by XVincentX** [comment]
@Tiberriver256 This is not exactly true. Thing is — the typings are reflecting the public API that the plugin framework is exposing, and it matches the documentation we have on our website.

However effectively we have a bunch of other properties that might be useful but we never settled down on whether we should expose them or not, and in case it's a yes — *HOW*.

If you feel some of these properties might be beneficial for you, feel free to open a new issue and we'll talk about it there. I'm going to close this in meantime.

Cheers!

**Comment by Tiberriver256** [comment]
Thanks @XVincentX. Good info. I asked a followup question for you via [StackOverflow](https://stackoverflow.com/questions/52905925/storing-additional-information-with-user-token-in-express-gateway). I might just be way off the path here.

**Comment by XVincentX** [comment]
Great! I’ll hop there later today!

**Comment by XVincentX** [comment]
@Tiberriver256 I briefly looked at your question. What you're trying to do is just great — I've never saw such use case for Express Gateway so far and I'll be willing to support you to make it happen.

I'll have an accurate review tomorrow and try to come up with something.

Thanks a lot!

**Comment by brandonros** [comment]
```
import * as path from 'path'
import * as gateway from 'express-gateway'

gateway()
  .load(path.join(__dirname, 'config'))
  .run();
```

```
node_modules/express-gateway/index.d.ts:15:14 - error TS7006: Parameter 'actionParams' implicitly has an 'any' type.

15       policy(actionParams): express.RequestHandler,
                ~~~~~~~~~~~~

node_modules/express-gateway/index.d.ts:21:37 - error TS7006: Parameter 'conditionConfig' implicitly has an 'any' type.

21       handler(req: express.Request, conditionConfig): boolean,
                                       ~~~~~~~~~~~~~~~

node_modules/express-gateway/index.d.ts:30:28 - error TS7006: Parameter 'cliExtension' implicitly has an 'any' type.

30       registerCLIExtension(cliExtension): void,
                              ~~~~~~~~~~~~

src/index.ts:4:1 - error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/Users/bros/repos/node-api-gateway/node_modules/express-gateway/index")' has no compatible call signatures.

4 gateway()
  ~~~~~~~~~
```

What am I doing wrong?..
