### ISSUE TITLE
AWS Lambda: prepare documentation for plugin

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#836]

**Comment by XVincentX** [comment]
@ravikp7 

It would be great if you could take care of this.

- [ ] Check out the source code of our [AWS Plugin](https://github.com/ExpressGateway/express-gateway-plugin-lambda)
- [ ] Try to install and use the plugin and see if that's working correctly using our [plugin installation guide](https://www.express-gateway.io/docs/cli/plugins/install/#description)
- [ ] Check out the docs and make sure they make sense and up to date
- [ ] Transcribe a new documentation page on our [documentation website](https://github.com/ExpressGateway/express-gateway.io/tree/gh-pages/docs/policies). Remember that this is not a core policy, so make sure to point it our in our docs in the same way we do for the "Rewrite" policy
- [ ] Update our [resource page](https://www.express-gateway.io/resources/) to add the icon (reach @altsang for the media files)
- [ ] Profit!

**Comment by XVincentX** [comment]
Fixed by @ravikp7 in express gateway/express-gateway.io#295
