### ISSUE TITLE
Bug: Issue completing "Getting Started" because of error

### ISSUE THREAD

**Issue by Nopskillz** [ExpressGateway/express-gateway#841]
I am behind a corporate proxy.  I have to set my proxy with a "npm config set https-proxy" command with my username and password.

When I follow the getting started tutorial, I've done everything correctly but when I run "npm start" I get an "unsupported proxy protocol" error in node_modules/proxy-agent-index.js:112

It appears to be trying to use my username for my proxy login as a protocol.

Please advise how to continue.

**Comment by XVincentX** [comment]
@Nopskillz `npm config set https-proxy` is setting the http proxy for the npm executable itself, it has nothing to do with node (thous Express Gateway).

To set such value for EG, you need to set the correct environment variable before starting Express Gateway itself.

Check https://www.express-gateway.io/docs/policies/proxy/#service-endpoints-behind-intermediate-proxy to have a better understanding of the feature.
