### ISSUE TITLE
add email mailing list sign up and intro to eg-cli

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#850]
_From @altsang on October 27, 2018 0:11_

null

_Copied from original issue: LunchBadger/general#516_

**Comment by altsang** [comment]
upon running the eg CLI for the first time we would like to print a welcome message:

Welcome to...

[eg-ascii-art.txt](https://github.com/LunchBadger/general/files/2622905/eg-ascii-art.txt)

Thanks for downloading Express Gateway! On behalf of its maintainers and the entire EG community, we hope you find Express Gateway useful for requirements.
Here are some userful links:

- getting started link
- documentation link
- gitter link
- commercial support link

Would you like to sign up for the EG mailing list?  Y/n <email pre-populated>

Claim your free sticker  - < link> , stop by and share your success story with us!  We constantly improve EG based on user feedback.

**Comment by XVincentX** [comment]
Ok I got it. I do not know how we can do this reliably in a CLI — I'll look into that.
