### ISSUE TITLE
How to modify login screen

### ISSUE THREAD

**Issue by anubhavr19** [ExpressGateway/express-gateway#854]
Hi... 

I am developing a micro-service project. I use express-gateway for api pipeline. I use built-in login. I want to know how to modify login screen and how to logout from this gateway.

**Comment by XVincentX** [comment]
Hey,

currently we do not really have a way to change the login screen programmatically. You basically need to fork the gateway and change some files internally which are building the view.

For the logout part, we offer a `/logout` endpoint which is destroying the current session, but no invalidating the token. Let me know in case you need further assistance — Gitter or StackOverflow are the preferred channels.

Cheers!
