### ISSUE TITLE
insertCredential fails when adding the second credential

### ISSUE THREAD

**Issue by devzsolt** [ExpressGateway/express-gateway#856]
Credential service's `insertCredential()` calls `getCredential()` which fails to consider the scenario when a credential is not a single hash but a set of hashes in the DB.

First it causes a warning: `WRONGTYPE Operation against a key holding the wrong kind of value`
which is followed by the following error:

```
TypeError: Cannot read property 'properties' of undefined at processCredential (/path-to-project/node_modules/express-gateway/lib/services/credentials/credential.service.js:255:51) 
  at s.getCredential.credentialDao.getCredential.then.credential (/path-to-project/node_modules/express-gateway/lib/services/credentials/credential.service.js:138:14) 
```

It's possible to reproduce always by creating a user with a credential and then deactivating the credential and creating a new one for the same user. Only key-auth and jwt type credentials are affected by the bug.

**Comment by XVincentX** [comment]
Thanks for the fix. I hope to be able to jump on this soon, I just didn't have the time.
