### ISSUE TITLE
Questions - EG's use as middleware

### ISSUE THREAD

**Issue by sido420** [ExpressGateway/express-gateway#863]
Thanks for this working on this project.

I haven't used it yet but planning to do so as it looks more interesting (in comparison to Kong at least).

However, I have a few quick questions:

- Can EG (or its plugins) be used as a middleware for an existing Express js application? I'm interested in using the Rate Limiter plugin as a middleware. How easy/difficult would it be to include it in an existing app?

- Can it proxy websocket traffic? 

- As a proxy/gateway, does it support sticky sessions?

- Is there a UI that lets you perform API actions easily?

**Comment by XVincentX** [comment]
Hey!

Thanks for considering Express Gateway — here are your answers!

> Can EG (or its plugins) be used as a middleware for an existing Express js application? I'm interested in using the Rate Limiter plugin as a middleware. How easy/difficult would it be to include it in an existing app?

EG does not offer such feature. The idea behind EG is exactly the opposite: extract such logic from your nodejs application in a different part of your stack — the API Gateway. That's the path you should pursue

> Can it proxy websocket traffic? 

Unfortunately, not yet. I know this is a feature that people will ask and ask more, but its implementation in the gateway is not trivial. There are different moving parts we'd need to fix before making it happen. In case that's really important for you, LunchBadger offers professional services/development on top of Express Gateway.


> As a proxy/gateway, does it support sticky sessions?
Sessions in EG are used exclusively to make the oAuth2 flow happen. Apart from that, they're not employed at all. If you can elaborate a little bit more, I can give you more details

> Is there a UI that lets you perform API actions easily?
Not natively, but again, LunchBadger provides such byproduct. https://www.lunchbadger.com/express-serverless-platform/ //cc @altsang
