### ISSUE TITLE
Lazy load policies

### ISSUE THREAD

**Issue by creising** [ExpressGateway/express-gateway#870]
Hi! I've been using Express Gateway on a project I am currently working on. It has been great to work with, thank you very much for the project!

I recently started implementing a custom policy for SAML authentication (using passport) and ran into a bit of an issue. It looks like when EG starts up it loads all of the policies that are included with it regardless if you are using them or not. It looks like the oauth2 policy adds a serializer and deserializer to passport when the module loads. Sadly, the deserializer was causing issues for me because Passport is invoking the oauth deserializer before mine and fails. 

I was wondering if there is a proper way to prevent modules from being loaded. If not, I was wondering if it would be worth it to add the ability to NOT load policies you're not using. Perhaps the loaded policies can be driven off of the `policies` array in the gateway's config file. 

I found a (hacky) workaround for now. Just wanted to check to make sure I am not missing anything.

Thanks!!!

**Comment by XVincentX** [comment]
Yeah this is something we’ve discussed multiple times and in general we think it makes sense. If you could file an issue with GitHub, I could properly track it and try to make it happen.

Cheers,

V.
