### ISSUE TITLE
"✖ Cannot read property 'properties' of undefined" when creating credentials after deactivating with CLI

### ISSUE THREAD

**Issue by ontehfritz** [ExpressGateway/express-gateway#884]
When you create credentials and want to deactivate and recreate the credentials it fails with:
✖ Cannot read property 'properties' of undefined

```
eg credentials create -c admin -t key-auth
eg credentials deactivate -t key-auth [put credential id here]
eg credentials create -c admin -t key-auth -p "scopes=admin"
```

throws exception: ✖ Cannot read property 'properties' of undefined

There should be a away to revoke credentials entirely.

**Comment by XVincentX** [comment]
I can't reproduce this — I've followed the instructions and I correctly got the error "one or more scopes do not exist"

I created the missing scope and I correctly received a new credential. Could you provide more details? Then feel free to reopen!
