### ISSUE TITLE
[Bug] "eg credentials create" hangs

### ISSUE THREAD

**Issue by willfe** [ExpressGateway/express-gateway#889]
While following the [Getting Started guide](https://www.express-gateway.io/getting-started/), at Part 3, Step 2, the following command hangs:

    eg credentials create -c bob -t key-auth -q

It produces no output and never returns to the command prompt. Removing the `-q` option still produces no output (and still hangs).

This is a fresh installation of express-gateway (installed via `npm install -g express-gateway` as instructed) and using the app generated by `eg gateway create`. The gateway is running, and previous steps in the guide work properly (that is, the gateway is properly forwarding requests to _httpbin_). The `gateway.config.yml` file has been updated as directed (uncommenting the `- key-auth:` line) and the gateway restarted automatically when the change was saved.

Note that adding and listing users appears to work normally. Only creating credentials seems to cause problems. Also noteworthy is that the credentials do appear to get created in Redis; they just never get printed to the console and `eg` never exits. `[ctrl]-[c]` works to kill the process, but then I need to look up the new credentials manually. That's going to get burdensome as I add more credentials for my current project.

Platform: Windows 10 Pro, build 17134.648, 64-bit. Node v11.11.0, npm 6.8.0. Redis 3.0.503 64-bit. All components are fresh installs, running natively (no docker or VM chicanery).

**Comment by XVincentX** [comment]
Thanks for the detailed report, I'll try to have a look into this.

**Comment by XVincentX** [comment]
@willfe I'm afraid this is a Windows only issue which might be a problem for me to reproduce, debug and try.

I had no problems on a MacBook.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/1416224/55092066-311e9780-50b2-11e9-9654-c1725340db1c.png">

I know that sucks, but I have no effective means to help you here.

**Comment by willfe** [comment]
Yeah, it works fine on Linux, too. Quirky little bug :)

No worries, I appreciate you checking it out anyway. I wouldn't be surprised at all if it's something dumb Windows is doing that gums up the works. If I figure anything out, I'll update this issue.

Thanks!

**Comment by willfe** [comment]
Update: it works when I use Git Bash instead of cmd.exe or Powershell, so it must be something to do with how Windows' built-in terminal interacts with express-gateway.

Unfortunately, issue #856 has surfaced now. I can add the first credential to a given user without incident, but any attempt to add further credentials to the same user yields "× Cannot read property 'properties' of undefined" as described in that issue.

**Comment by XVincentX** [comment]
Thanks for the report. I'm a little bit swamped but I still hope to have a look into :)

**Comment by XVincentX** [comment]
This does not appear to be an issue anymore in node12 — and it seems to be confirmed by our tests in Azure pipelines. Please reopen in case you're still experiencing it.

**Comment by bshea5** [comment]
I'm running into the same issue described above, on both node12 and 13 on Windows 10. Can this bug be re-opened?

![image](https://user-images.githubusercontent.com/3984775/76717927-64f33280-66f2-11ea-8014-3ef512f90339.png)

**Comment by souris-dev** [comment]
I'm also encountering the same issue on node v14.4 on Windows 10. It would be great if this issue could be reopened.

![image](https://user-images.githubusercontent.com/5001953/140978127-157c4b03-b8c5-4a9b-b11f-eebfa93ef4af.png)
![image](https://user-images.githubusercontent.com/5001953/140978304-b62c7cd4-99cd-4ad8-b768-41b6a406f778.png)
