### ISSUE TITLE
Fastfiy implementation

### ISSUE THREAD

**Issue by mhf-ir** [ExpressGateway/express-gateway#896]
How about implement fastify instead of express:

https://github.com/fastify/fastify#benchmarks
https://docs.nestjs.com/techniques/performance

**Comment by XVincentX** [comment]
Nice try!

In theory it would be awesome, in practice this is not going to happen. When we started the project we named it after the project we wanted to take advance of: Express.

Having two backend implementation is nor worth nor easy to maintain, so I'm afraid this is not going to happen anytime soon (probably never).
