### ISSUE TITLE
[Question] use ws: true, but connection disconnect after accept

### ISSUE THREAD

**Issue by HobaiRiku** [ExpressGateway/express-gateway#897]
Trying to proxy websocket connection in EG, i read the doc, and add `ws: true` at `action`, the `upgrade` protocol is proxy to the `serviceEndpoint`, but it disconnect immediately like this: 
![image](https://user-images.githubusercontent.com/26238803/55319340-3e1efa80-54a7-11e9-974b-b89556d33387.png)
using `websocket` in npm start the server demo.

and i try to write a plugin like `express-gateway-pulgin-example`, and use `proxy.ws()` in `http-ready`, and the target is point to the `serviceEndpoint`  directly, it work, but that is not what i want.

Then  i try to search about `proxy.ws()` in source code, can't see it but `proxy.web()` which is use to proxy `http`. 

Any method to proxy `ws` like `http` ？

**Comment by XVincentX** [comment]
We do not effectively support websocket right now. That parameters is unfortunately not correct and we'll remove it from there asap.

**Comment by Davide-DD** [comment]
is websocket support still in development?

**Comment by XVincentX** [comment]
Hey,

Unfortunately EG development has been halted, and I do not plat to work on this anytime soon.

Sorry about that,

V.
