### ISSUE TITLE
Rewrite policy missing

### ISSUE THREAD

**Issue by selfagency** [ExpressGateway/express-gateway#903]
The rewrite policy is missing from the `lib/policies` folder.

**Comment by selfagency** [comment]
Just went through a year's worth of commit history— looks like it never existed in the first place. It's in the docs though.

**Comment by XVincentX** [comment]
The rewrite policy is indeed a plugin, as specified in the docs.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/1416224/55750539-cc652480-5a43-11e9-9c3f-031a97e89560.png">
