### ISSUE TITLE
Is it possible to use custom authentication

### ISSUE THREAD

**Issue by exotfboy** [ExpressGateway/express-gateway#913]
The document under `Secure the API with Key Authorization` in the [get strated](https://www.express-gateway.io/getting-started/) said that we should create user  in `express-gateway`, and eg will genreate key for the user which the application will take for requesting.

However generally, different application may have its own user/roles service, and the keys may be generated by the application itself. So I wonder if we can create a custom policy which will extract key infomation either jwt or other keys, and then valid that using our bussiness databse.

Is this possible?

**Comment by XVincentX** [comment]
I'd suggest you to leave this question on StackOverflow, it's going to be way easier to have a discussion there.

To answer your question — ideally your web application can create new users and roles using Express Gateway Admin API, leaving to it the management of all your stuff there.

Does that clarify?
