### ISSUE TITLE
Suggestion: proxy policy allowing dynamic serviceEndpoint 

### ISSUE THREAD

**Issue by AnsonT** [ExpressGateway/express-gateway#914]
We have a scenario where the proxied service endpoint depends on some component on the path. It would be great if the service endpoint can be a fully formatted href, instead of just an index into the service endpoint array. This will allow the href to be formatted with available variables, or better yet, rewritten with a rewrite policy.

**Comment by XVincentX** [comment]
@AnsonT 

Interesting…would it be possible to provide an example of what you're trying to achieve? That might provide the necessary context to tame the issue.

According to the information you provided you're looking for a dynamic routing that (maybe) EG does not really provide (at least right now).

**Comment by XVincentX** [comment]
@AnsonT I'm closing this since you did not provide any more details. It would be great if you could elaborate more though, the use case might be interesting.

**Comment by AnsonT** [comment]
@XVincentX Sorry for the late reply. Our scenario is with microservices where our PR (pull request, test) builds have build numbers in the kubernetes service names: e.g. xyz.service1. We would like to dynamically route to one of these services based on e.g. a cookie value in our dev environment.

**Comment by manwegit** [comment]
I'm also faced with N to N mapping api gateway to add centralized API-authkey management to existing services. The other service models I've looked at look too heavy (memory/cpu/resource/infrastrure -wise). I'm also running kubernetes.

I'll see what I come up with. At least it can be "hacked"-in like:
https://stackoverflow.com/a/50477763/1142796
