### ISSUE TITLE
dead depdency http-proxy

### ISSUE THREAD

**Issue by mhf-ir** [ExpressGateway/express-gateway#918]
`http-proxy` seems be dead:
https://github.com/nodejitsu/node-http-proxy/issues/1341

How about create better package than `http-proxy`.
It's not maintain anymore. See issue and pull request pending

**Comment by XVincentX** [comment]
Hey,

that would be really neat but Express Gateway is effectively missing the required manpower to make it happen unfortunately. It's basically only me. You might want to look to other forks you can find on the web

**Comment by DerMika** [comment]
One of the dependencies of `redbird` appears to be `"http-proxy": "^1.17.0",`

**Comment by XVincentX** [comment]
I know – but still the new project enhances the experience a lot. The dependency does not really matter I guess, as long it works, right?
