### ISSUE TITLE
eg gateway create hangs

### ISSUE THREAD

**Issue by fawmi** [ExpressGateway/express-gateway#919]
### eg gateway create hangs

In `eg gateway create`, `in Where would you like to install your Express Gateway?` the terminal hang out, I cannot type anything, I can't event use ctr+c to cancel the command.

I tried using node v12.4.0 and v10.16.0 and both versions having the same problem.

Here are my system information(if relevant):
MacBook Pro (15-inch, 2017) with osx majove
eg version: 1.16.4

**Comment by XVincentX** [comment]
Thanks for the note, I'm going to check it out and see if I can reproduce/fix it

**Comment by XVincentX** [comment]
I'm not able to reproduce it. Can you post a screenshot/video or something?

**Comment by fawmi** [comment]
I will post a screenshot/video tomorrow, but I don't think it would be that helpful. I will try to reproduce it in my windows machine or a linux VM.
I will try to debug it myself.

**Comment by XVincentX** [comment]
Yeah the thing is we have the test suite running this command on Mac, Windows and Linux. I've tried on my personal computer as well and I haven't really been able to reproduce it.

There's probably something going on, but without more context or stuff it's going to be hard to help you.

That said, I want to get rid of yeoman and that crap anyway. It *could be* that a simple package update could resolve the problem, though.

**Comment by fawmi** [comment]
I thing, it had something todo with my terminal setup. I have uninstalled `oh my zsh, removed `powerline fonts` and switched to bash shell.  Now it works fine.
