### ISSUE TITLE
[Bug] Policy display in case of missing

### ISSUE THREAD

**Issue by celian-garcia** [ExpressGateway/express-gateway#923]
## Description
Hello guys, this is a really minor bug, but, in the field ``policies`` of the ``gateway.config.yml`` file, if you use a policy that does not exist, it displays a message that does not contain the missing policy.

## Reproduce

gateway.config.yml
```yaml
http:
  port: 8000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
policies:
  - name: toto
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
```

## What we see

npm start
```
...
2019-06-23T07:31:29.739Z [EG:policy] error: Could not find policy [object Object], Please make sure the plugins providing such policy
     is correctly configured in system.config file.
...
```
## What we should see

npm start
```
...
2019-06-23T07:31:29.739Z [EG:policy] error: Could not find policy 'toto', Please make sure the plugins providing such policy
     is correctly configured in system.config file.
...
```

**Comment by XVincentX** [comment]
Your configuration is indeed invalid — that's why you're seeing an incorrect error message. It should be

```diff
- name: toto
+ toto
```

In any case, the schema should have catch that. 1f29dca fixes this.

Thanks!

**Comment by celian-garcia** [comment]
Ah yeah thanks, maybe you could consider to modify this part of documentation ? https://www.express-gateway.io/docs/configuration/gateway.config.yml/policies/

**Comment by XVincentX** [comment]
Done!
