### ISSUE TITLE
CORS origin option doesn't check for RegExp in array

### ISSUE THREAD

**Issue by Matthbo** [ExpressGateway/express-gateway#924]
I have made an example gateway.config.yml:
```http:
  port: 8080
apiEndpoints:
  api:
    host: localhost
    paths: '*'
serviceEndpoints:
  example:
    url: 'https://example.com'
policies:
  - cors
  - proxy
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - {cors: [{action: {origin: ['https://example.com',  /https:\/\/w*\.example.com$]}}]}
      - {proxy: [{action: {serviceEndpoint: example}}]}
```
When I try to fetch from `https://www.example.com` it should return without having a CORS problem, however it seems like the`Access-Control-Allow-Origin` isn't sent.

It does work if I change `origin: ['https://example.com',  /https:\/\/w*\.example.com$]` to `origin: ['https://example.com',  'https://www.example.com']`.

The fault isn't the RegExp, I checked it [here and it seems to work just fine](regexr.com/4gqig).
This would mean that while stated [in the docs](https://www.express-gateway.io/docs/policies/cors/#options-reference) `origin` doesn't check for RegExp.

**Comment by XVincentX** [comment]
You need to properly instruct the yaml parser you are providing a regepx and not a simple string

```diff
- - {cors: [{action: {origin: ['https://example.com',  /https:\/\/w*\.example.com$]}}]}
+ - {cors: [{action: {origin: ['https://example.com', !!js/regexp /https:\/\/w*\.example.com$]}}]}
```
