### ISSUE TITLE
Get /users /apps /credentials returning empty

### ISSUE THREAD

**Issue by surykv** [ExpressGateway/express-gateway#931]
Hi,

We have deployed Express Gateway in one of our environments. We have used redis to store users, apps and credential info.
I'm facing one strange issue. 

When I do a GET /users (Index call) , it is returning empty. 
{
    "users": [],
    "nextKey": 0
}

When I fetch a specific user, it is returning the value.
For eg GET /users/test returns the below
{
    "isActive": true,
    "username": "test",
    "id": "8bd48733-15e2-4c75-a980-cc60893a7da7",
    "firstname": "test",
    "lastname": "express",
    "email": "steve@example.com",
    "createdAt": "Tue Jul 16 2019 11:18:02 GMT+0000 (UTC)",
    "updatedAt": "Tue Jul 16 2019 11:18:02 GMT+0000 (UTC)"
}

Is there any setting required to make the Index call work?

**Comment by XVincentX** [comment]
What's the redis version you're using?
What's the express gateway version are you using?

This bug seems to be indeed very strange.

**Comment by surykv** [comment]
Yeah, this is very strange, 

We are using Express Gateway version 1.16.4
Redis version 3.2.12

**Comment by XVincentX** [comment]
@surykv oh I see. So we've been starting to test Express Gateway with Redis 4 and 5; we've never tested the software with Redis 3. I believe this might be the reason. Is there any chance you can upgrade?

**Comment by surykv** [comment]
@XVincentX Sure, let me check with my devops team and get back

**Comment by surykv** [comment]
@XVincentX I have upgraded redis.
Now /apps, /credentials are working.
/users is still returning emtpy

**Comment by surykv** [comment]
I'm able to consistently reproduce this all the environments we have.
GET /users alone is returning empty though there are users

**Comment by XVincentX** [comment]
All right in this case I'll need to set up an instance and check it out :)

**Comment by surykv** [comment]
@XVincentX Thank you, appreciate it :)

**Comment by surykv** [comment]
@XVincentX Hi, I deployed again today morning. Same issue started to happen for /apps, /credentails also. I'm doubting if this has something to do with redis version.
The express gateway is the latest one forked from this repository.
Any immediate help is appreciated. Thanks in advance!

**Comment by XVincentX** [comment]
I can correctly see the created users @surykv. Can you show me the the CURL call you're doing to create the user?

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/1416224/61692784-8d2abd00-ad2e-11e9-9c08-429baafe35de.png">

**Comment by surykv** [comment]
@XVincentX  I've modified the default gateway.config.yml like below
http:
  port: '${EG_HTTP_PORT:-8080}'
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: '*'
    paths:
      - /admin/*
serviceEndpoints:
  backend:
    url: 'http://localhost:9876'
policies:
  - proxy
  - key-auth
pipelines:
  adminAPI:
    apiEndpoints:
      - api
    policies:
      - proxy:
          action:
            serviceEndpoint: backend
            prependPath: true
            ignorePath: false
            stripPath: true

CURL for creating users:
curl -X POST \
  'http://{{eg_url}}/admin/users' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: c2836656-535b-468d-8602-d54b30ca2fe6' \
  -H 'cache-control: no-cache' \
  -d '{
  "username": "test",    
  "firstname": "test", 
  "lastname": "express",   
  "email": "steve@example.com"
}'

Screenshot for GET calls - 

![Screen Shot 2019-07-23 at 1 11 39 PM](https://user-images.githubusercontent.com/47710552/61699129-6038d300-ad4b-11e9-8d3d-a99c130c47a1.png)


@XVincentX Can you tell me ur express gateway version and redis version? I'll cross check on my side.

**Comment by XVincentX** [comment]
@surykv Can you try to fill the `redirectUri` field as well? That might be the bug/issue. If you could confirm that, I could work on a fix.

**Comment by surykv** [comment]
Its not working :( I tried... Is there any log statements that I can add in the code to debug this better?

**Comment by XVincentX** [comment]
Unfortunately this part is not exactly that easy to debug. I'll have to ask you some more patience, I'll try to jump on this during the weekend or so.

**Comment by surykv** [comment]
Thanks, will wait for the update

**Comment by XVincentX** [comment]
@surykv I've done yet another test with a real Redis instance and it's still working correctly for me

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/1416224/61991889-ecead600-b056-11e9-858b-bfbaa0d41047.png">

I've been using the `redis:latest` docker image and the code directly from the master branch.

I have no idea how to help you further unfortunately.
