### ISSUE TITLE
req.on('response') not working in plugins

### ISSUE THREAD

**Issue by jayhjha** [ExpressGateway/express-gateway#934]
I'm creating a custom policy plugin to transform response. Since EG middleware is essentially express middleware, I tried to add a listener for `response` event:
```
policy: () => (req, res, next) => {
  req.on('response', () => {
  }
}
```
But the `response`  event is never triggered, and neither is any of the other events for `HttpClientRequest` (https://nodejs.org/api/http.html#http_class_http_clientrequest).

For context, I'm creating a plugin to transform the response body. But the response I'm getting from the server is in chunks (header set to `Transfer-Encoding: chunked`)
Overriding `res.write`, as described [here](https://github.com/ExpressGateway/express-gateway/blob/master/lib/policies/response-transformer/index.js) doesn't work because I have to join all the chunks before doing any transformation.

**Comment by jayhjha** [comment]
Any updates on this? 
I'm still unsure about `req`, `res` in a policy plugin. 
The event emitters usually available for Express middleware req & res don't seem to be available in the plugin.

**Comment by XVincentX** [comment]
I think you're confusing two parts — the `response` event is triggered by the `ClientRequest` which is an object that you get when you're doing a request from a _client_, not from a server.

The object you get from a plugin is an instance of [IncomingMessage](https://nodejs.org/api/http.html#http_class_http_incomingmessage)

I hope this clarifies!

**Comment by jayhjha** [comment]
@XVincentX thanks for getting back to me.
In express middleware, req is indeed an instance of IncomingMessage.

Does the EG plugin act as server-side middleware, then? Because the [request-transformer policy](https://github.com/ExpressGateway/express-gateway/blob/master/lib/policies/request-transformer/index.js), transforms the request using a similar policy and I guess that's where I'm a little confused how the plugin handles both requests from the client and response from the service.

Also, when proxying the request to a service, is it possible to add listeners to that request using plugins?

**Comment by XVincentX** [comment]
> Does the EG plugin act as server-side middleware

That is correct, EG is a server side middleware between the client and your upstream service!

> Also, when proxying the request to a service, is it possible to add listeners to that request using plugins?

Yes, you can!

> plugin handles both requests from the client and response from the service.

This depends on what you're trying to accomplish. If you could elaborate more what's your end game I can probably point you towards the right direction (and maybe update the documentation, so this confusion vanishes forever) :)

**Comment by jayhjha** [comment]
@XVincentX  thanks for looking into this.

I have a policy plugin which is based on the [response-transformer](https://github.com/ExpressGateway/express-gateway/blob/master/lib/policies/response-transformer/index.js). I'm overriding the `res.write` as well. 

The difference is that the service sending the response is sending it in chunks, so the `data` in 
```
return (req, res, next) => {
  res.write = (data) => { 
    JSON.parse(data)
  }
}
```
is an invalid JSON. In this specific case the response from the service is sent in 3 chunks, and all 3 chunks combined make a valid JSON.
But the policy is trying to parse the JSON data for each chunk which obviously fails.

I thought the `req` in this case is the request that's being proxied to my service and I could just add a `req.on('response')` event listener and wait for the full response to be received before doing `JSON.parse()`. But like you pointed out, req is an instance of `IncomingMessage` so there's no `response` event. What would you recommend in this case?

**Comment by xinjiguaike** [comment]
> @XVincentX thanks for looking into this.
> 
> I have a policy plugin which is based on the [response-transformer](https://github.com/ExpressGateway/express-gateway/blob/master/lib/policies/response-transformer/index.js). I'm overriding the `res.write` as well.
> 
> The difference is that the service sending the response is sending it in chunks, so the `data` in
> 
> ```
> return (req, res, next) => {
>   res.write = (data) => { 
>     JSON.parse(data)
>   }
> }
> ```
> 
> is an invalid JSON. In this specific case the response from the service is sent in 3 chunks, and all 3 chunks combined make a valid JSON.
> But the policy is trying to parse the JSON data for each chunk which obviously fails.
> 
> I thought the `req` in this case is the request that's being proxied to my service and I could just add a `req.on('response')` event listener and wait for the full response to be received before doing `JSON.parse()`. But like you pointed out, req is an instance of `IncomingMessage` so there's no `response` event. What would you recommend in this case?

same problem with you, have you any solutions to solve this？

**Comment by XVincentX** [comment]
I guess you could be using a streaming serialiser (you can pick up any on NPM) to accumulate the buffer and then send it once calling the original `_write`.

**Comment by xinjiguaike** [comment]
> I guess you could be using a streaming serialiser (you can pick up any on NPM) to accumulate the buffer and then send it once calling the original `_write`.

 can you give an example, I really have no idea how to process with this !
