### ISSUE TITLE
Need supporting Client Token with API Gateway + JWT

### ISSUE THREAD

**Issue by sangnguyen7** [ExpressGateway/express-gateway#939]
I have been using JWT token for handling authentication and authorization for my micro-services. I think JWT is a great solution when working with micro-services and scalability but also come with some challenging when revoking or using with browser.  So there is a solution as described below: 

The authentication process of the user is similar to the basic process of token authentication. The difference is that the API Gateway is added as the entrance of the external request. This scenario means that all requests go through the API gateway, effectively hiding the micro-services. On request, the API gateway translates the original user token into an opaque token that only itself can resolve like the following diagram:
![image](https://user-images.githubusercontent.com/4648887/63996149-77907c00-cac0-11e9-950c-54d4ef2ccaf1.png)

In this case, logging off is not a problem because the API gateway can revoke the user’s token when it logs out and also it adds an extra protection to Auth Token from being decrypted by hiding it from the client.

[reference here](https://medium.com/tech-tajawal/microservice-authentication-and-authorization-solutions-e0e5e74b248a)

However, it seems that the current version of Express Gateway does not support this feature yet. So that would be great if EG could support this feature!

Thanks,
~Sang

**Comment by XVincentX** [comment]
I understand your use case — however the solution you're proposing is not something described in any RFC and so you need to write your own policy for that.

In case you need to revoke the JWT — I'd rather switch to another technology (such as cookies, they work just great for this) or — if you really want this, use the JWT in controlled mode, where you can effectively say "this token is not ok anymore"

https://www.express-gateway.io/docs/policies/jwt/
