### ISSUE TITLE
Error message should 'failed to activate user'

### ISSUE THREAD

**Issue by retailify** [ExpressGateway/express-gateway#940]
https://github.com/ExpressGateway/express-gateway/blob/e5837a1790d3005f0f9f31210abde4febfbbdafd/lib/services/consumers/user.service.js#L115

**Comment by XVincentX** [comment]
Can you provide more details?

**Comment by retailify** [comment]
Hi @XVincentX, 

in the activate method you are trying to activate the user. When this does'nt work the Promise should return, that the activation not work (and not the deactivation). 

```javascript
s.activate = function (id) {
  return this.get(id) // make sure user exists
    .then(function () {
      return userDao.activate(id);
    })
    .then(() => true)
    .catch(() => Promise.reject(new Error('failed to deactivate user')));
};
```

**Comment by XVincentX** [comment]
Good point — are you ok opening a PR for that?

**Comment by retailify** [comment]
yes I can fix that.
