### ISSUE TITLE
Question: is keep alive supported

### ISSUE THREAD

**Issue by creising** [ExpressGateway/express-gateway#945]
Hello! Thank you all for the work you’re doing on Express-Gateway.

This might just be a lack of knowledge on my part, but I recently encountered an issue where the proxy plugin was changing the connection field in the headers of my request from keep-alive to close. For us, it would be great if keep-alive was supported. I started poking around and I think that this might be happening in http-proxy. I found this post https://github.com/http-party/node-http-proxy/issues/767 which seems to indicate that it is the agent’s responsibility to handle keep-alives which I believe in express-gateway’s case is proxy-agent. From what I could tell does not mention support for this.
At this point I did not see anything that I could do from the configuration standpoint to enable keep-alives, but I thought I would ask just to make sure I am not missing something super obvious.

Thank you again for your time!

**Comment by XVincentX** [comment]
We're effectively using the ProxyAgent for intermediate proxy purposes, but we aren't really setting any meaningful option. Will try to address this.
