### ISSUE TITLE
Policy OAuth2-Introspect not empty scannedTokens

### ISSUE THREAD

**Issue by fcioffi** [ExpressGateway/express-gateway#953]
Hi guys,

in my investigation i undesrstand that oauth2-introspect policy do not empty scannedTokens constant with previous accessTokens inspected.

Are there someone that can help me?
Thanks a lot!

**Comment by XVincentX** [comment]
I’m not so sure I understand the issue you’re referring to. Can you elaborate a little bit more?

V.

**Comment by fcioffi** [comment]
Looking in the file:
express-gateway/lib/policies/oauth2-introspect/oauth2-introspect.js

```
tokenIntrospection(accessToken, 'access_token')
      .then(tokenData => {
        scannedTokens[accessToken] = { lastCheck: Date.now(), tokenData };

        return scopeCheck(tokenData, done);
      })
      .catch(() => { done(null, false); });
  }));
```
the line:
` scannedTokens[accessToken] = { lastCheck: Date.now(), tokenData };`
write in scannedTokens the accessToken object.

The question is: when scannedTokens is emptied?

Thanks a lot!
FC

**Comment by fcioffi** [comment]
@XVincentX it's clear now?
Thanks,
FC

**Comment by XVincentX** [comment]
It's never emptied. We do not have any clear policy for that.

**Comment by fcioffi** [comment]
So, the policy is unusable in production environment, do you agree?
Do you know if is there an enhancement in roadmap?

**Comment by XVincentX** [comment]
@fcioffi 

> So, the policy is unusable in production environment, do you agree?

I would say it depends on your requirements. What are you looking for? Why keeping the tokens in memory would be a problem?

> Do you know if is there an enhancement in roadmap?

Frankly speaking, the roadmap is frozen at the moment. Essentially I do not have the time to work on Express Gateway at all and although great companies are using it, nobody has ever been willing to help in development (in terms of code or financially). Therefore, no improvements are planned as long nothing moves on this side.

**Comment by tagkiller** [comment]
@fcioffi maybe you could write a fix for it ? I mean just checking `((Date.now() - scannedTokens[accessToken].lastCheck) / 1000) >= actionParams.ttl` and then remove the token from the list each time the strategy is used should do the job.

**Comment by fcioffi** [comment]
Hi @tagkiller, @XVincentX,
I could write a fix for it. Furthermore, I would like to use the DB for store tokens, also. I thought if is possibile to use expiration at Redis level, but I must investigate yet.
If I write an enhancement, are you willing to accept it?
Thanks,
Francesco

**Comment by XVincentX** [comment]
It is not currently using Redis, the data is stored in memory.

I am willing to accept a fix, for sure.

**Comment by fcioffi** [comment]
@XVincentX, @tagkiller,
pull request sent :=)
Let me know.

**Comment by XVincentX** [comment]
Merged, thanks.
