### ISSUE TITLE
Bad gateway 502 [EG:policy] warn: socket hang up

### ISSUE THREAD

**Issue by aqieez** [ExpressGateway/express-gateway#962]
After implementing https with certifcate and key. When I call API endpoint I getting Bad gateway 502 in Postman. And [EG:policy] warn: socket hang up is showing in logs of the express gateway. I don't know what is wrong. I can't figure it out. Please help

**Comment by XVincentX** [comment]
You might want to provide further details — in this way there's not enough information to help you out.

**Comment by leeogrady** [comment]
First resource I found when troubleshooting, despite being old i'll update it.
I had the same error, running EG in docker on 6080:8080. 
My EG config had a serviceEndpoint as localhost:8080. 
Presumably this was then calling localhost in the EG container, not back to the host to another container running on 8080. 
Using the host IP resolved the issue. 
Expect only relevant to localdev.
