### ISSUE TITLE
How to request to service with query string parameters and custom headers?

### ISSUE THREAD

**Issue by nguyencongvu** [ExpressGateway/express-gateway#966]
I can manage Kong API and new to Express gateway. I am ok with the starter guide, but cannot config how to 
1- Request to serviceEndpoint with querystring (ex: https://domain.com?token=1234)
2- Request to serviceEndpoint with custom header (ex: request to  https://rapidapi.com/apilayernet/api/rest-countries-v1)  

I search everywhere (glitter, stackoverflow, docs...) but cannot 
Please help. 
@rlisagor @dougwilson @kevinswiber @bploetz @ddunkin

**Comment by XVincentX** [comment]
1. That is not supported unfortunately, since merging the query string wouldn't be that easy
2. You should probably use the header policy
