### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by TalhaSiddique10** [ExpressGateway/express-gateway#967]
its@dits-Y11C:~$ cd testing && npm start

> testing@1.0.0 start /home/dits/testing
> node server.js

2019-11-24T15:40:04.836Z [EG:gateway] info: gateway http server listening on :::8080
2019-11-24T15:40:04.838Z [EG:admin] info: admin http server listening on 127.0.0.1:9876

I am using this command and the installation stuck in this step.
Kindly help in this issue.

**Comment by wjlewis** [comment]
This actually looks like the expected behavior to me. What does your config directory look like?

**Comment by XVincentX** [comment]
The gateway is indeed running. Feel free to reopen when you have more details
