### ISSUE TITLE
Policy Creation

### ISSUE THREAD

**Issue by neerajnegidev** [ExpressGateway/express-gateway#974]
is there any way to create own policy and put it source code inside root directory e.g. inside express-gateway/policy?
How to register policy from root location of project. As per documentation it will be done through manifest.js init function, but i am not able to see manifest.js  file anywhere.

**Comment by MohammadWasi** [comment]
@neerajnegidev you need a plugin for that. 
for more information please go to this link- https://www.express-gateway.io/docs/plugins/plugin-development/#example-plugin-package-overview

**Comment by code-angels** [comment]
I'm a bit confused about this. Does this imply that it is not possible to apply a policy as custom middleware ( like you would with a regular Express application) without explicitly writing an external plugin and registering it?
